### ISSUE TITLE
ability to convert enums

### ISSUE THREAD

**Issue by harishrathi** [frhagn/Typewriter#100]
Can you please add ability or if its already there, then can you please add an example of how to convert enums from cs to ts on your examples page.

**Comment by frhagn** [comment]
Try something like this:
```
$Enums(Filter)[enum $Name {
    $Values[
    $Name = $Value][,]
}]
```

**Comment by sachabest** [comment]
How does Typewriter find enums that would go into the filter? Even with an empty filter parameter and enums declared in my C#, the template doesn't generate any files.

**Comment by rvalimaki** [comment]
Try adding "*" into filter instead of an empty one.

**Comment by sachabest** [comment]
Thank you! For some reason a filter that takes in an argument of type enum and simply returns true was not picking up anything. Is that the right signature?

**Comment by jcorrea-origin** [comment]
$Classes(e=>e.Namespace == "Common.Entities" && e.NestedEnums.Count()>0)[
         module Models.Commons.Entities {   
            export module $Name {
                $NestedEnums[
                    export enum $Name {
                        $Values[
                            $Name = $Value][,]
                    }
                ]
            }
         }
       ]

**Comment by JBoothUA** [comment]
this should be in the docs somewhere but great to find!  thanks!
