### ISSUE TITLE
Help for Milestone 2.0

### ISSUE THREAD

**Issue by SeriousM** [frhagn/Typewriter#107]
Hi Fredrik,

as far as I can see, the Milestone 2.0 is aimed to drop the CodeDom support and use only Roslyn, right?
I would like to help you with the first step and cleanup the solution drom CodeDom code.
It would be a big help if you could create a new public branch (named v2.0 or something like hat) where I can push my PRs to.

What do you think?

**Comment by frhagn** [comment]
Hi @SeriousM, 
thanks for your interest in helping out with Typewriter. Your help is much appreciated!

I'm currently testing out some different ideas and concepts in a separate private repo. The new code base is very volatile at the moment and not really ready to be merged into the Typewriter repo. I'm also considering creating a new repo for 2.0 so for now I think it's a good idea to lay low with working on 2.0 in the current repo.
The work is moving along pretty good and when the new code structure is set I'll publish it to GitHub in some form.

**Comment by SeriousM** [comment]
Alright, just let me know when you need help or the code is ready to be
touched.
Typewriter is awesome!

**Comment by ichpuchtli** [comment]
I want to help as well. This is an amazing project. I think it has massive potential aswell auto generating crud from entity framework.

**Comment by agustinbcu01** [comment]
Hi @frhagn.

Do you have any ETA for this milestone?
@rodro75 have a pretty nice implementation for share template, and I planing to use it in my workplace.   
Regards
