### ISSUE TITLE
remove module on code generation.

### ISSUE THREAD

**Issue by lilling** [frhagn/Typewriter#110]
I write in angular 2 so there's no need for typescript module. can I disable it?

**Comment by frhagn** [comment]
Hi @lilling, the generation is template based so if you remove the module parts from the tst template it will be removed from the generated files.
```
$Classes(some filter)[
    class $Name {
        ...
    }
]
```

**Comment by lilling** [comment]
Im pretty new in this. Can you please give me a working example?
בתאריך 18 במאי 2016 12:02,‏ "Fredrik Hagnelius" <notifications@github.com>
כתב:

**Comment by frhagn** [comment]
Check out http://frhagn.github.io/Typewriter/pages/getting-started.html and 
http://frhagn.github.io/Typewriter/pages/examples.html for more info on how to get started.

**Comment by lilling** [comment]
Thabk you very much!
בתאריך 18 במאי 2016 12:11,‏ "Fredrik Hagnelius" <notifications@github.com>
כתב:
