### ISSUE TITLE
typewriter doesn't handle nested RESTful routes properly

### ISSUE THREAD

**Issue by gregveres** [frhagn/Typewriter#112]
Hi Fredrik

I am trying to use Typewriter for the first time. I have to say I am impressed with the tool and the concept of the tool. Great job!

I have run into a problem where typewriter isn't handling a nested RESTful API properly. In my interface, I have a court group, which has a list of courts. So the API for the court groups is handled properly with the  route extension.

Here is the first method of my court group controller:

```
    [Authorize]
    [RoutePrefix("api/CourtGroups")]
    public class CourtGroupsController : OurBaseApiController
    {

        /// <summary>
        /// Returns the list of Court Groups.
        /// </summary>
        /// <returns>an array of CourtGroup objects</returns>
        [HttpGet]
        public IList<CourtGroup> GetAllCourtGroups()
        {
```

and typewriter correctly turned it into:

```
module Api.CourtBooking {
    
    export class CourtGroupsService {
        

        // get: api/courtGroups/
        public static RouteGetAllCourtGroups = () => `api/courtGroups/`;
        public static getAllCourtGroups(): JQueryPromise<CourtGroup[]> {
            return $.ajax({
                url: CourtGroupsService.RouteGetAllCourtGroups(),
                type: 'get',
                data: null
            });
        }

```

My .tst file looks like this:

```
${
    using Typewriter.Extensions.WebApi;

    string ReturnType(Method m) => m.Type.Name == "IHttpActionResult" ? "void" : m.Type.Name;
    string ServiceName(Class c) => c.Name.Replace("Controller", "Service");
    string ParentServiceName(Method m) => ServiceName((Class)m.Parent);
}

module Api.CourtBooking {
    $Classes(SquashSpider.API.Controllers.CourtBooking.*)[
    export class $ServiceName {
        $Methods[

        // $HttpMethod: $Url
        public static Route$Name = ($Parameters(p => p.Type.IsPrimitive)[$name: $Type][, ]) => `$Url`;
        public static $name($Parameters[$name: $Type][, ]): JQueryPromise<$ReturnType> {
            return $.ajax({
                url: $ParentServiceName.Route$Name($Parameters(p => p.Type.IsPrimitive)[$name][, ]),
                type: '$HttpMethod',
                data: $RequestData
            });
        }]
    }]
}
```
I stole this .tst file from this article: 
http://kamranicus.com/blog/2016/02/04/typewriter/

Now what happens when I have a nested REST interface, one for courts that live within a court group is this:

here is my controller:

```
    [Authorize]
    [RoutePrefix("api/CourtGroups/")]
    public class CourtsController : OurBaseApiController
    {
        /// <summary>
        /// Returns the list of Courts for a CourtGroup.
        /// </summary>
        /// <param name="GroupId">the id of the court group</param>
        /// <returns>an array of Court objects</returns>
        [Route("{GroupId}/Courts")]
        [HttpGet]
        public IList<Court> GetAllCourts(int GroupId)
        {

```

and here is what typewriter outputs:

```
        // get: api/CourtGroups/${GroupId}/Courts?groupId=${groupId}
        public static RouteGetAllCourts = (groupId: number) => `api/CourtGroups/${GroupId}/Courts?groupId=${groupId}`;
        public static getAllCourts(groupId: number): JQueryPromise<Court[]> {
            return $.ajax({
                url: CourtsService.RouteGetAllCourts(groupId),
                type: 'get',
                data: null
            });
        }

```

Notice the double parameters in the $url. I think the capitalization is my problem. But the double GroupId is the problem. I originally had the {GroupId} in the RoutePrefix but the output from Typewriter was the same. I would prefer to have it in the RoutePrefix since {GroupId} shows up in every one of my Court controller's URLs. 

This seems to be a valid route case that the WebAPI extension doesn't handle properly. 

Any suggestions? 

Thanks 
Greg

**Comment by gregveres** [comment]
As a quick follow up, I was looking at a different web service on the same courts controller and noticed another problem. Here is the controller: 

```
        [HttpPost]
        [Route("{GroupId}/Courts/")]
        public IHttpActionResult AddCourt(int GroupId, Court court)
        {
```

and this is what was generated:

```
        // post: api/CourtGroups/${GroupId}/Courts/
        public static RouteAddCourt = (GroupId: number) => `api/CourtGroups/${GroupId}/Courts/`;
        public static addCourt(GroupId: number, court: Court): JQueryPromise<void> {
            return $.ajax({
                url: CourtsService.RouteAddCourt(GroupId),
                type: 'post',
                data: { groupId: groupId, court: court }
            });
        }

```

Notice in the data, there is an extra groupId: groupId. There should only be a court: court because the groupId is sent as part of the Url. I think this is all related but I wanted to point out this case as well. 

Thanks
Greg

**Comment by frhagn** [comment]
Hi @gregveres 
It seems Typewriter incorrectly camel-cases the route parameters when creating the url, I'll add a fix for this.. Meanwhile you should be able to get working by camel-casing the route parameters and the method parameters e.g.
```
[HttpPost]
[Route("{groupId}/Courts/")]
public IHttpActionResult AddCourt(int groupId, Court court)
{
```

**Comment by gregveres** [comment]
Hi @frhagn 

Yes the camel case is one issue, but that can be worked around. Did you notice the other issue where it doesn't handle a parameter in the route? It generated the URL as: 

`        public static RouteGetAllCourts = (groupId: number) => `api/CourtGroups/${GroupId}/Courts?groupId=${groupId}`;`


Notice the groupId in there twice, once as part of the URL path and once as a parameter. That is the issue that I don't see a way to work around. 

I just wanted to make sure you saw that issue too. 

Thanks
Greg

**Comment by frhagn** [comment]
I think camel casing the parameters should solve the second issue as well.. Do you still get the extra quert string parameter even after camel casing?

**Comment by gregveres** [comment]
Ah I see what you mean. You are correct. Once I changed the first letter of my parameters from upper case to lower case, typewriter started to behave perfectly. Thank you very much for the full work around while I wait for an update. 

I love this tool. It has made things so much simpler. Thank you!

**Comment by frhagn** [comment]
Cool, I'm working on the fix now so it'll be available soon

**Comment by gregveres** [comment]
I just came across another instance where it isn't creating the proper URL, I think. I might be missing something though. 

Here is my controller:

  ```
  [Authorize]
    [RoutePrefix("api/[Controller]")]
    public class CourtGroupsController : OurBaseApiController
    {
        [HttpPost]
        [HttpPut]
        public IHttpActionResult EditCourtGroup(int groupId, CourtGroup group)
        {
        }
   }
```

and my .tst file:

```
${
    using Typewriter.Extensions.WebApi;

    string ReturnType(Method m) => m.Type.Name == "IHttpActionResult" ? "void" : m.Type.Name;
    string ServiceName(Class c) => c.Name.Replace("Controller", "Service");
    string ParentServiceName(Method m) => ServiceName((Class)m.Parent);
}

module Api.CourtBooking {
    $Classes(SquashSpider.API.Controllers.CourtBooking.*)[
    export class $ServiceName {
        $Methods[

        // $HttpMethod: $Url
        public static Route$Name = ($Parameters(p => p.Type.IsPrimitive)[$Name: $Type][, ]) => `/$Url`;
        public static $name($Parameters[$Name: $Type][, ]): JQueryPromise<$ReturnType> {
            return $.ajax({
                url: $ParentServiceName.Route$Name($Parameters(p => p.Type.IsPrimitive)[$Name][, ]),
                type: '$HttpMethod',
                data: $RequestData
            });
        }]
    }]
}
```

it generated: 

```
module Api.CourtBooking {
    
    export class CourtGroupsService {
        
        // post: api/courtGroups/
        public static RouteEditCourtGroup = (groupId: number) => `/api/courtGroups/`;
        public static editCourtGroup(groupId: number, group: CourtGroup): JQueryPromise<void> {
            return $.ajax({
                url: CourtGroupsService.RouteEditCourtGroup(groupId),
                type: 'post',
                data: { groupId: groupId, group: group }
            });
        }

```

Notice that groupId is pushed down as a body parameter rather than a URL parameter.  I have to admit I don't really know how Visual Studio knows that groupId should be a URL parameter, but it does. Even the API Help pages catch it as a URL parameter. 

But as a work around, I can rename groupId to just id and then Typewriter knows that id should be a URL parameter. So I will go with that for now.

**Comment by gregveres** [comment]
I have tried this in 1.7.4 and it is all working now. 

Thanks for the fix!
Greg
