### ISSUE TITLE
Do the attributes parameters capture data validation attributes?

### ISSUE THREAD

**Issue by gregveres** [frhagn/Typewriter#114]
Hi @frhagn 

I am trying to figure out how to do validation using Knockout and ASP.Net MVC. They don't play very nice together. 

So I turned my attention to the knockout validation plugin. It requires me to put the validation methods on the javascript model class. So I turned to Typewriter for a solution. If Typewriter can do this I would be a very happy camper. 

I have used Data validation attributes on my c# DTO that is being converted into a typescript class using typewriter. Does the Attribute Collection in typewriter include the data validation attributes? 

I tried just dumping out the attribute array but I didn't get anything at all so I figure I am doing something wrong. 

Here is my c# class:

```
    public class ApiCourtGroupsViewModel
    {
       
        public class CourtGroup
        {
            public int CourtGroupId { get; set; }

            [Required]
            [StringLength(5)]
            public String Name { get; set; }

            public String Description { get; set; }

            [Required]
            [RegularExpression("^([1-9]|1[0-2]):([0-5]\\d)\\s?(a|p|A|P)(m|M)$")]
            public string StartingTime { get; set; }

```

and my .tst file is:

```
${
    string KnockoutType(Property p) {
        if (p.Type.IsEnumerable) {
            return p.Type.Name.TrimEnd('[',']');
        }

        return p.Type;
    }

    string KnockoutValue(Property property) {
        var type = KnockoutType(property);

        if (IsEnumerableViewModel(property)) {
            return $"ko.observableArray<Knockout{type}>([])";
        } else if (property.Type.IsEnumerable) {
            return $"ko.observableArray<{type}>([])";
        }

        return $"ko.observable<{type}>()";
    }

    bool IsEnumerableViewModel(Property p) {
        string type = KnockoutType(p);

        return p.Type.IsEnumerable && type.EndsWith("ViewModel");
    }
}
namespace Api.CourtBooking {
    $Classes(SquashSpider.API.ViewModels.CourtBooking.*)[$NestedClasses[
    /**
     * Interface for: $FullName
     */
    export interface $Name {
        $Properties[
        $Name: $Type;]
        $Attributes[
        FullName: $FullName;
        Name: $Name;
        name: $name;
        Parent: $Parent;
        Value: $Value;]
    }

```

the only thing that was output were the properties. 

Thanks
Greg

**Comment by gregveres** [comment]
Ah I figured out what I was doing wrong. Where I had the Attributes array, I was trying to print the attributes of the class and there were no attributes on the class.

I moved the Attributes[] keyword inside the Properties[] array and voila I got all the attributes of the properties. Wow. this is great. 

Now I just have to figure out how to convert that into input for the knockout validation plugin. When I figure that out I will post an example back here.

**Comment by gregveres** [comment]
I haven't done the work to add the validation yet, I will at some point, but for now, I will close this. No need keeping this one open for no reason.

**Comment by danielmeza** [comment]
I get the attributes but i cannot chec if tey are instances of ValidationAttribute class beacause the references to the using System.ComponentModel.DataAnnotations is missing so when I get the attribute Type I get AttributeIpm instances of the real type from the attribute.

**Comment by frhagn** [comment]
@danielmeza, try using `attribute.Name == "..."` or `attribute.BaseClass?.Name == "..."`.
