### ISSUE TITLE
a bug with $Url not picking up a parameter

### ISSUE THREAD

**Issue by gregveres** [frhagn/Typewriter#118]
HI @frhagn 

I have a case where the WebApi extension $Url isn't correct. 

Here is the c# controller code:

```
    [Authorize]
    [RoutePrefix("api/BoxLeague")]
    public class BoxLeagueController : OurBaseApiController
    {
...
        [HttpPost]
        [Route("{id}/Rejoin")]
        public string RejoinPlayer(int id, [FromUri] int playerId)
        {
...
```

What this produces is a URI like
/api/BoxLeague/${id}/Rejoin?playerId=${playerId}

Here is the .tst file I am using:

```
${
    using Typewriter.Extensions.WebApi;

    string ReturnType(Method m) => m.Type.Name == "IHttpActionResult" ? "void" : m.Type.Name;
    string ServiceName(Class c) => c.Name.Replace("Controller", "Service");
    string ParentServiceName(Method m) => ServiceName((Class)m.Parent);
}

module BoxLeague.Manage {
    $Classes(SquashSpider.API.Controllers.League.BoxLeagueController)[
    export class $ServiceName {
        $Methods[

        // $HttpMethod: $Url
        public static Route$Name = ($Parameters(p => p.Type.IsPrimitive)[$Name: $Type][, ]) => `/$Url`;
        public static $name($Parameters[$Name: $Type][, ]): JQueryPromise<$ReturnType> {
            return $.ajax({
                url: $ParentServiceName.Route$Name($Parameters(p => p.Type.IsPrimitive)[$Name][, ]),
                type: '$HttpMethod',
                data: $RequestData
            });
        }]
    }]
}

```

Here is what Typewriter produces:

```
        // post: api/BoxLeague/${id}/Rejoin
        public static RouteRejoinPlayer = (id: number, playerId: number) => `/api/BoxLeague/${id}/Rejoin`;
        public static rejoinPlayer(id: number, playerId: number): JQueryPromise<string> {
            return $.ajax({
                url: BoxLeagueService.RouteRejoinPlayer(id, playerId),
                type: 'post',
                data: playerId
            });
        }

```
Here is what the code should produce:

```
       // post: api/BoxLeague/${id}/Rejoin
        public static RouteRejoinPlayer = (id: number, playerId: number) => `/api/BoxLeague/${id}/Rejoin?playerId=${playerId}`;
        public static rejoinPlayer(id: number, playerId: number): JQueryPromise<string> {
            return $.ajax({
                url: BoxLeagueService.RouteRejoinPlayer(id, playerId),
                type: 'post',
                data: null
            });
        }
```

I put the [FromUri] in the parameter list to see if Typewriter was picking that up. It doesn't. BTW, notice that in the incorrect code, the $parameters are correct. It has both parameters, but the $Url only has one parameter in it. And notice that the $RequestData should be null but it has the second parameter in it. 

Since Typewriter was working this way, I thought I might be able to get ASP.Net Web API to accept the playerId parameter in the body by putting [FromBody] in front of the parameter but that didn't work. So at the moment the only work around I have is to change the generated .ts file every time the .tst template renders. 

Thanks
Greg

**Comment by frhagn** [comment]
Hi @gregveres,
for some reason Typewriter only handled GET and HEAD requests correctly. I just published a new patch-version (1.7.3) that fixes this problem.

**Comment by gregveres** [comment]
Perfect. I will pick up that new version and give it a try.

**Comment by gregveres** [comment]
@frhagn 

This works great for my example. You can consider this closed. 

Thanks for the fix.
Greg
