### ISSUE TITLE
Method.Parent (Class) is of the Wrong Type

### ISSUE THREAD

**Issue by SeriousM** [frhagn/Typewriter#120]
The parent of a method is the original declaring type.

Example:

```
class BaseClass
{
  void DoSomething();
}

class Car : BaseClass
{
}
```

Therefore, Car.DoSomething's Parent is BaseClass.
The problem is that the classes sometimes have attributes (eg. RoutePrefix).

Example:

```
[RoutePrefix("api/base")]
class BaseController : ApiController
{
  void FireEvent(){}
}

[RoutePrefix("api/car")]
class CarController : BaseController
{
}
```

Therefore, CarController.FireEvent's Parent is BaseController and so is the RoutePrefix "appi/base".

Is it possible to get the parent of the method (property, field, etc) where the type is visible at (in this case, CarController)?

**Comment by frhagn** [comment]
Hi @SeriousM,
`$Parent` is the parent context of the current item so you can get the `RoutePrefix` of `CarController` by starting at the top level e.g.
```
$Classes(CarController)[
    $Name // CarController
    $BaseClass[
        $Name // BaseController
        $Methods[
            $Name // FireEvent
            $Parent[
                $Name // BaseController
                $Parent[
                    $Name // CarController
                    $Attributes(RoutePrefix)[
                        $Value // "api/base"
                    ]
                ]
            ]
        ]
    ]
]
```

**Comment by SeriousM** [comment]
Well, that's kind of right if I know the concrete class, but I start with `$Classes(c => c.Name.EndsWith("Controller")` which gives me not the right type of class in $Class.

**Comment by frhagn** [comment]
I'm afraid there's no way to get the concrete class(es) from `$Class` so you'll have to handle this in some other way, maybe add a more specific filter to exclude the base class?
`$Classes(c => c.Name.EndsWith("Controller") && c.BaseClass?.Name != "BaseController")`
