### ISSUE TITLE
Map Property Types

### ISSUE THREAD

**Issue by JayCallas** [frhagn/Typewriter#123]
Is there a way to customize the transformation of specific C# data types to TypeScript? For example, on one C# class there is a property with the type `KeyValuePair<string, number>` which could translate to a Dictionary (typed Dictionary even??) or, at the very least, an empty object `{ }` in JavaScript.

**Comment by aluanhaddad** [comment]
You would write a helper like
```C#
string MapTypeName(Property property) 
    {
        var typeArguments=  property.Type.TypeArguments.ToList();
        return typeArguments.Count == 2 
            && property.Type.Name ==  $"KeyValuePair<{typeArguments[0]}, {typeArguments[1]}>"
                ? $"[{typeArguments[0]}, {typeArguments[1]}]"
                : property.Type;
    }
```
That gives you back a string but you could return other information as well.
