### ISSUE TITLE
change $Type in &Properies by condition.

### ISSUE THREAD

**Issue by radziksh** [frhagn/Typewriter#125]
Hi, I need replace **Date** type in **C#** to **string** type in **Typescript**, something like this:
```
$Classes(ReservationApiModel)[
    interface $Name { $Properties[
        if($Type == Date){
            $name: string;
        }else{
            $name: $Type;
        } 
    ]}
]
```
how can I do it?

**Comment by frhagn** [comment]
Hi @radziksh 
You can use $IsDate[true template][false template] e.g.
...
$Properties[
    $name: $Type[$IsDate[string][$Name]];
]
...

**Comment by radziksh** [comment]
@frhagn, thank you, it works.

**Comment by aluanhaddad** [comment]
@frhagn I didn't know about this feature. This will let me get rid of a bunch of helpers for things like moment. Thanks!
