### ISSUE TITLE
Error rendering template

### ISSUE THREAD

**Issue by jmvtrinidad** [frhagn/Typewriter#136]
**NOTE** I tried already reinstall or disabled the plugin.

**Here's the output from TypeWriter.**

> 16:05:20.465 ERROR: Error rendering template. Cannot get identifier 'Classes'. Source path: D:\Path\CustomerModel.cs
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Typewriter.Metadata.CodeDom.CodeDomFileMetadata.get_Classes()
>    at Typewriter.CodeModel.Implementation.FileImpl.get_Classes()

**TST file**
```
${
    // Enable extension methods by adding using Typewriter.Extensions.*
    using Typewriter.Extensions.Types;

    // Uncomment the constructor to change template settings.
    //Template(Settings settings)
    //{
    //    settings.IncludeProject("Project.Name");
    //    settings.OutputExtension = ".tsx";
    //}

    // Custom extension methods can be used in the template by adding a $ prefix e.g. $LoudName
    string LoudName(Property property)
    {
        return property.Name.ToUpperInvariant();
    }
}
module Helper {

    // $Classes/Enums/Interfaces(filter)[template][separator]
    // filter (optional): Matches the name or full name of the current item. * = match any, wrap in [] to match attributes or prefix with : to match interfaces or base classes.
    // template: The template to repeat for each matched item
    // separator (optional): A separator template that is placed between all templates e.g. $Properties[public $name: $Type][, ]

    // More info: http://frhagn.github.io/Typewriter/

    $Classes(*Model)[
    export class $Name {
        $Properties[
        public $name: $Type = $Type[$Default];]
    }]
}
```
 **Here's my VS Info**
Microsoft Visual Studio Ultimate 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Ultimate

Architecture and Modeling Tools   06181-004-0451031-02179
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Team Explorer for Visual Studio 2013   06181-004-0451031-02179
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06181-004-0451031-02179
Microsoft Visual Basic 2013

Visual C# 2013   06181-004-0451031-02179
Microsoft Visual C# 2013

Visual C++ 2013   06181-004-0451031-02179
Microsoft Visual C++ 2013

Visual F# 2013   06181-004-0451031-02179
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06181-004-0451031-02179
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   06181-004-0451031-02179
Windows Phone SDK 8.0 - ENU

AbstraLabs.TypeScriptDiagram   1.0
Add the ability to generate diagrams from TypeScript.

Add New File   3.5
The fastest and easiest way to add new files to any project - including files that start with a dot

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   12.5.60612.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Web Apps
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30612.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.4
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Durandal extensions for Visual Studio 2013   1.0
Information about my package

Entity Framework Power Tools   1.0
Adds useful design-time DbContext features to the Visual Studio Solution Explorer context menu. 

When right-clicking on a file containing a derived DbContext class, the following context menu functions are supported:

1) View Entity Data Model - Displays the underlying Code First model in the Entity Framework designer.
2) View Entity Data Model XML - Displays the EDMX XML representing the underlying Code First model.
3) Generate Views - Generates pre-compiled views used by the EF runtime to improve start-up performance. Adds the generated views file to the containing project.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

InstallShield Limited Edition   
InstallShield. For more information visit the Flexera Software website at <http://www.FlexeraSoftware.com>. Copyright © 2013 Flexera Software LLC. All Rights Reserved.

JetBrains ReSharper Ultimate 2016.1.2    Build 105.0.20160522.80219
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

KnockoutGenerator   1.0
Generate C# Model to a Knockout ViewModel

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Team Foundation Server 2013 Power Tools   12.0
Power Tools that extend the Team Foundation Server integration with Visual Studio.

Microsoft Visual Studio Process Editor   1.0
Process Editor for Microsoft Visual Studio Team Foundation Server

MySQL for Visual Studio   1.2.3
Data design and management tools for MySQL.  Copyright © 2007-2014 Oracle, Inc.

NuGet Package Manager   2.12.0.817
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   12.0.41012.0
Microsoft SQL Server Data Tools

Typewriter   1.0
Provides automatic TypeScript Template generation from C# source files

Web Essentials 2013   2.6.13.0
Adds many useful features to Visual Studio for web developers.

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

**Comment by jmvtrinidad** [comment]
I also  try to render template and it says `Not Implemented Exception from HRESULT: 0x80004001 (E_NOTIMPL))`.

**Comment by frhagn** [comment]
Hi @jmvtrinidad,
I'm afraid I don't really have any idea why you get this issue.. Have you tried to reproduce the issue in a clean solution containing only the files necessary to render a single ts file?

**Comment by jmvtrinidad** [comment]
I try it on a clean solution and it works. Maybe there's something weird in solution. Thanks.
