### ISSUE TITLE
Pull commonalities between Interface, Class and Type into a C# Interface

### ISSUE THREAD

**Issue by aluanhaddad** [frhagn/Typewriter#141]
This project exhibits some very nice coding practices. For example, _inheritance_ is not overused! This is great. 
However, I think _implementation_ could be used in more places to make it easier to write generic helper functions.
For example the `Class`, `Interface`, and `Type` types have a common abstract base class `Item` with non members. However, they have much in common from an API perspective.

I frequently find myself wanting to write a method that would operate uniformly over their common properties.

For example I have written a helper like this

``` C#
    // Gets the kebab-cased, simple filename corresponding to the symbolic name
    string FileNameFromTypeName(string name) =>
        name.Select((c, i) => (char.IsUpper(c) && i > 1 ? "-" : string.Empty) + c)
            .Aggregate(
                seed: string.Empty,
                func: (fileName, segment) => fileName + segment,
                resultSelector: fileName => fileName.ToLower()
            );

string ModuleName(Class @class) => FileNameFromTypeName(@class.name);
string ModuleName(Interface @interface) => FileNameFromTypeName(@interface.name);
string ModuleName(Type type) => FileNameFromTypeName(type.name);
string ModuleName(Property property) => FileNameFromTypeName(property.Type.name);
string ModuleName(string type) => FileNameFromTypeName(type);
```

Obviously this is not a terrible amount of extra work, but it quickly becomes more complex.

``` C#
IEnumerable<Type> PropertyTypes(Type type) =>
    from property in type.Properties
    let propertyType = property.Type.Unwrap()
    where !propertyType.IsPrimitive
        || propertyType.IsDate
        || propertyType.IsEnum
    group propertyType by propertyType.Name into g
    let property = g.First()
    orderby ModuleName(property).StartsWith("./")
    select property;

IEnumerable<Type> PropertyTypes(Class @class) =>
    from property in @class.Properties
    let propertyType = property.Type.Unwrap()
    where !propertyType.IsPrimitive
        || propertyType.IsDate
        || propertyType.IsEnum
    group propertyType by propertyType.Name into g
    let property = g.First()
    orderby ModuleName(property).StartsWith("./")
    select property;

IEnumerable<Type> PropertyTypes(Interface @interface) =>
    from property in @interface.Properties
    let propertyType = property.Type.Unwrap()
    where !propertyType.IsPrimitive
        || propertyType.IsDate
        || propertyType.IsEnum
    group propertyType by propertyType.Name into g
    let property = g.First()
    orderby ModuleName(property).StartsWith("./")
    select property;
```

I realize I could still reduce code duplication, which I abhor, without this change, but I also want to be able to abstract.
My proposal is to introduce an `interface`, perhaps named `IType`, that would declare common properties such as `Interfaces`, `NestedClasses`, `FulleName`, etc.

This would make maintaining helpers much easier. It would also allow templates to be more readable and maintainable.
For example I need to add this to generate the `import` clauses 

``` ts
$Interfaces[import $Name from '$ModuleName';
]
$BaseClasses[import $Name from '$ModuleName';
]
$PropertyTypes[import $ImportTypeName from '$ModuleName';
]
```

Let me know what you think, I would be happy to submit a PR.

**Comment by Jonatthu** [comment]
I think this must be on the project

**Comment by aluanhaddad** [comment]
Actually, I've started using `dynamic` to reduce the boilerplate
