### ISSUE TITLE
Use System.ComponentModel.DataAnnotations.* in .tst Templates 

### ISSUE THREAD

**Issue by jay1891** [frhagn/Typewriter#143]
First of all I want to say that Typewriter is amazing! This is a tool with a lot of potential, and I love it. :)

I have 2 questions:

  1) Is it possible to read/use data annotations like DisplayAttribute and RangeAttribute in a tst template?

  2) Is it possible to also read/use custom attributes or call custom code in a tst template?

**Comment by jay1891** [comment]
I noticed I can read the properties and its attributes on the Typewriter.Codemodel.Class . On every attribute there is attribute.Name & attribute.Value. The value contains the data annotation parameters, so in this way it is possible to read the attribute.

**Comment by frhagn** [comment]
Hi @jay1891,
check out http://frhagn.github.io/Typewriter/pages/getting-started.html#custom-methods end http://frhagn.github.io/Typewriter/pages/examples.html for some info on using custom methods in tst templates.

**Comment by jay1891** [comment]
Hi,

Thank you for your info. I'm using this approach intensively and thank you that you made this available. 

Because I'm getting to much code inside the templates, I was hoping if I could call own custom dlls (external code) and maybe can for example call more libraries like the dataannotations. Also reusing code between different templates would be nice.

But with the current possibilities I can find a solution.
