### ISSUE TITLE
Newtonsoft.Json.Linq.JObject parameter crashes Visual Studio 2015

### ISSUE THREAD

**Issue by Oblomoff** [frhagn/Typewriter#144]
Typewriter 1.8

A class containing a method with parameter of type Newtonsoft.Json.Linq.JObject crashes Visual Studio 2015. The problem in Parameter.Type property I guess.
cs
```C#
    public class MyClass
    {
        public void MyMethod(Newtonsoft.Json.Linq.JObject myParameter)
        {
            
        }
    }
```
tst
```TypeScript
$Classes(*)[$Methods[$name($Parameters[$name: $Type])]]
```
Exampe solution is here.

[ClassLibrary.zip](https://github.com/frhagn/Typewriter/files/542063/ClassLibrary.zip)

**Comment by frhagn** [comment]
Fixed in 1.8.1, kudos on the perfect example solution @Oblomoff!
