### ISSUE TITLE
CamelCase bug

### ISSUE THREAD

**Issue by jods4** [frhagn/Typewriter#146]
CamelCase incorrectly transforms `IsIG` to `isig`. Expected result is `isIG`.

The bug seems to be this condition
```csharp
if (i > 0 && hasNext && char.IsUpper(chars[i + 1]) == false)
{
  break;
}
chars[i] = char.ToLowerInvariant(chars[i]);
```
It fails when `i == 0` and the next character is lower case.
I think a more correct logic would be to always lowercase i == 0, then continue if the current char and the next one both are uppercase.
Something like (untested):
```csharp
if (i > 0 && !(char.IsUpper(chars[i]) && hasNext && char.IsUpper(chars[i + 1])))
  break;
```
Note: I am unsure what the correct behavior is for `ABC`. Code above results in `abC`.

**Comment by frhagn** [comment]
Good find @jods4, fixed in 1.8.2
