### ISSUE TITLE
right clicking and selecting Render template crashing

### ISSUE THREAD

**Issue by gregveres** [frhagn/Typewriter#149]
HI @frhagn 

This just started happening to me: when I right click on a .tst file and select Render template, I get an exception from VS. The exception is 

`Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))`

I am running VS Community 2015
version 14.0.25431.01 Update 3

I don't know exactly when this started happening - maybe when I upgraded to Update 3?

Is anybody else seeing this?

Greg

**Comment by captainjono** [comment]
Yep i am seeing this, just installed today with VS2013 update 5.

**Comment by chadbengen** [comment]
I suddenly started getting this message with VS 2015 update 3, but it had been working previously.  Thinking I had a corrupt environment I reinstalled windows and VS 2017.  I am still receiving this with a clean reinstall.

**Comment by frhagn** [comment]
See #168
