### ISSUE TITLE
Ability to loop through classes without creating files

### ISSUE THREAD

**Issue by tunwin819** [frhagn/Typewriter#150]
For example, I have the following code the create a service for each ApiController in my project:

```
$Classes(:ApiController)[
    
@Injectable()
export class $ServiceName {

    constructor(public http:Http ){  }

    $Methods[
        

    $name = function($Parameters[$name: $Type][, ]) : Observable<any> //See if token is still valid
    {
            return this.http.$HttpMethod(this.baseUrl + '$Url', $RequestData, { headers: headers })
                .map((resp: Response) => resp.json())
                .catch((error:any) => {
                    return Observable.throw(error);
                });
        });
    }

]
```

I also want to be able to include imports at the top of this file for all my generated types (generated using Typewriter too!) Something like this at the top of the template:

```
$Classes(*Model)[
    import { $Name } from '../../../models/$Name';
]
```

This currently creates lots of extra files, for each *Model class. It would be nice to be able to list them all of in this one file.

**Comment by frhagn** [comment]
Hi @tunwin819,

Unfortunately it's not possible to combine files the way you want. However you should be able to achieve the end result you're after using a different approach. e.g.

```
${
    using Typewriter.Extensions.Types;

    string Imports(Class c)
    {
        return string.Join(Environment.NewLine, c.Methods.Select(m => 
            $"import {{ {m.Type.ClassName()} }} from '../../../models/{m.Type.ClassName()}'"
            ).Distinct());
    }
}
$Classes(:ApiController)[

$Imports
    
@Injectable()
export class $ServiceName {

    constructor(public http:Http ){  }

    $Methods[
    $name = function($Parameters[$name: $Type][, ]) : Observable<$Type> //See if token is still valid
    {
            return this.http.$HttpMethod(this.baseUrl + '$Url', $RequestData, { headers: headers })
                .map((resp: Response) => resp.json())
                .catch((error:any) => {
                    return Observable.throw(error);
                });
        });
    }
]
```

**Comment by VadimPanov** [comment]
Hi frhagn,

Where $Imports and $ServiceName come from? There is nothing of the sort in https://frhagn.github.io/Typewriter/pages/documentation.html ...

**Comment by frhagn** [comment]
Hi @VadimPanov, `$Imports` and `$ServiceName` are custom template methods implemented in the code block at the top of the template (though `$ServiceName` is omitted in the example above). 

See https://frhagn.github.io/Typewriter/pages/getting-started.html#custom-methods for more info.
