### ISSUE TITLE
Lambda Filtering on custom List<Property>

### ISSUE THREAD

**Issue by lexon0011** [frhagn/Typewriter#151]
We want to return all Properties (from the base Classes too) and be able to Filter them like $Properties. The custom function in use is:

```
List<Property> getAllPropertiesForClass(Class c) {
    List<Property> props = new List<Property>();
    Class currentClass = c;
    while(currentClass != null) {
        foreach(Property prop in currentClass.Properties) {
            props.Add(prop);
        }
        currentClass = currentClass.BaseClass;
    }
    return props;
}
```

The Problem with this function is that typewriter ignores Filtering e.g.

- `$Properties(p => p.HasSetter)` -> Just Properties with Setter are returned
- `$getAllPropertiesForClass(p => p.HasSetter) ` -> All Properties from the List are returned (filtering does **NOT** working)

Is it possible to instantiate a new PropertyCollection or can we do something else to enable this sort of filtering?

**Comment by frhagn** [comment]
Hi @lexon0011,
I'm afraid there's no support for filtering the result of custom methods. What you can do is to move the fileter inside the custom method e.g.
```
List<Property> getAllPropertiesForClass(Class c) {
    List<Property> props = new List<Property>();
    Class currentClass = c;
    while(currentClass != null) {
        foreach(Property prop in currentClass.Properties) {
            props.Add(prop);
        }
        currentClass = currentClass.BaseClass;
    }
    return props.Where(p => p.HasSetter).ToList();
}
```
