### ISSUE TITLE
Visual Studio 2017 Support

### ISSUE THREAD

**Issue by aluanhaddad** [frhagn/Typewriter#152]
It would be great to be able to install this extension into Visual Studio 2017. 

I know that in the long term you plan to maintain separate plugins for separate Visual Studio versions but I don't know how far off that goal is. In the meantime, I want to use this plugin in Visual Studio 2017.

Thank you.

**Comment by frhagn** [comment]
Hi @aluanhaddad,
I'm working on this but I'm having some problems with publishing to Visual Studio Gallery while still maintaining compatibility with vs 2013 and 2015. I updated to the new RC version of 2017 yesterday and got a bit further, but I'm not all the way done yet..

**Comment by aluanhaddad** [comment]
I just accidentally came across Typewriter in the Extensions and Updates browser for VS2017. I installed it and it is working wonderfully. Thanks @frhagn!!

**Comment by frhagn** [comment]
Fixed in 1.9.0

**Comment by mikebagheri** [comment]
I am trying to install the extension, but it fails. I am using Visual Studio 2017 Enterprise RC (15.0.26020.0).

Before I was using this in Visual Studio 2015 and it is great.

Any Idea why it fails to install in 2017 RC?
