### ISSUE TITLE
Generic base class type parameter not correct

### ISSUE THREAD

**Issue by rob123456** [frhagn/Typewriter#153]
When I externalize the following two classes to typescript I end up with the corresponding typescript:
` public class Wrapper<T>{} public class WrapperExtender<T1,T2> : Wrapper<T1> {}`
`interface Wrapper<T>{}; interface WrapperExtender<T1,T2> : Wrapper<T> {}`

It appears that class.BaseClass.TypeParameters goes directly to the BaseClass' definition and uses the type parameter names from there. I think it should actually be using the Type parameters specified in C# on the WrapperExtender declaration i.e. I would expect `interface WrapperExtender<T1,T2> : Wrapper<T1> {}` to be outputted in typescript.

A simple workaround is to change the C# definition to `public class WrapperExtender<T,T2> : Wrapper<T> {}` but that feels like a cheat. Is there a better way to get around this?

**Comment by frhagn** [comment]
Hi @rob123456,

`TypeParameters` gives you the type parameters from the source class. However, if you use `TypeArguments` instead you'll get the type arguments specified where the class is used instead e.g.

```
$Classes(Wrapper*)[
    interface $Name$TypeParameters $BaseClass[extends $Name$TypeArguments] {
        //...
    }
]
```

**Comment by rob123456** [comment]
Hi @frhagn Thanks for your help, that was exactly what I was looking for!
