### ISSUE TITLE
Arbitary C# Method definition breaks custom extension expression evaluation

### ISSUE THREAD

**Issue by aluanhaddad** [frhagn/Typewriter#154]
I added the following method to my `.tst` file
```C#
IEnumerable<Type> MethodGroupTypes(Class @class) => 
    from method in @class.Methods 
    group method by method.Name
    into g from m in g 
    orderby m.Parameters.Count 
    select m.Type;
```
after doing so, custom extensions were no longer evaluated. That is to say that any `$m` and `$m[$p]` expressions in say `$Classes[...]` were simply emitted as `$m` and `$m[$p]`.

Commenting out the method definition causes evaluation to work as expected. I have reproduced in multiple templates with 100% success.

Here is a minimal repro
```C#
${
    IEnumerable<Type> MethodGroupTypes(Class @class) => 
        from method in @class.Methods 
        group method by method.Name
        into g from m in g 
        orderby m.Parameters.Count 
        select m.Type;

    string Expr(Class @class) => @class.Name;

    string MExpr(Method method) => method.Name;


}$Classes(:ApiController)[
$Expr

export class $Name {
$Expr
  $Methods[
    $MExpr
    $name($Parameters[$name: $Type][, ]): $Type {$MExpr
    }
  ]
}]
```
this emits, for say `AccountRegistrationController.cs` the following TypeScript
```ts

$Expr

export class AccountRegistrationController {
$Expr
  
    $MExpr
    register(model: AccountRegistrationViewModel): void {$MExpr
    }
  
    $MExpr
    validateToken(model: TokenViewModel): AccountRegistrationViewModel {$MExpr
    }
  
    $MExpr
    confirmAccount(model: AccountConfirmationViewModel): void {$MExpr
    }
  
    $MExpr
    validateEmail(vm: ValidateEmailViewModel): IHttpActionResult {$MExpr
    }
  
}
```

**Comment by frhagn** [comment]
Hi @aluanhaddad,
There was a problem with getting the correct type from the generated template assembly when using Linq-statements in the template. I've fixed the issue, but I still haven't been able to publish the new version to Visual Studio Gallery yet due to some issues with adding support for vs 2017..

**Comment by aluanhaddad** [comment]
@frhagn awesome! Thank you for the quick turn around, as well as for the explanation!

I am glad to hear that VS 2017 support is in active progress too ❤️
