### ISSUE TITLE
Abstract classes?

### ISSUE THREAD

**Issue by riiight** [frhagn/Typewriter#155]
Is there a way to determine if a class is abstract or not so that I can add the "abstract" keyword to the TS class? If not, I think that would be a very helpful feature. Also, if anyone has any workarounds for this, I'd appreciate hearing them.

**Comment by frhagn** [comment]
Hi @riiight,
I'm afraid it's not possible to determine if a class is abstract in the current version (1.10.0).. 
I'll look into adding this functionality

**Comment by riiight** [comment]
Ok, thanks.

**Comment by aluanhaddad** [comment]
@riiight I guess it could be useful, and this is not exactly relevant, but deep class hierarchies serialized and mapped from C# to JavaScript and back sound like an absolute nightmare.

This is especially if you plan to use, or end up needing to use, ```instanceof``` in JavaScript/TypeScript as part of your design.
```instanceof``` in JavaScript/TypeScript has drastically different semantics in JavaScript than they `is` in C# or `instanceof` in Java.

If you are trying to generate models/DTOs, this is bad idea. 

If you are trying to generate services there are other ways.

**Comment by gravidThoughts** [comment]
@aluanhaddad Could you elaborate further about the relationship between models/DTOs and complex abstract C# class hierarchies? I am trying to formulate a strategy for using a preexisting C# model from Web API to an Angular client with TypeScript.

**Comment by frhagn** [comment]
Support for `$IsAbstract` added in 1.11.0
