### ISSUE TITLE
Extract Value from EnumMemberAttribute on EnumValue

### ISSUE THREAD

**Issue by thegreatco** [frhagn/Typewriter#157]
I have an API Wrapper written in C# and I want to share the POCOs with a TypeScript implementation.

I have an enum where the values are deserialized from a JSON API. I have changed the names slightly in the C# enum to better match C# standards. This means I use `EnumMember(Value = "xxx")` to decorate each enum value. 

I am using the following Typewriter definition
```
$Enums(PingMeSharp.Model.*)[
    export type $Name = $Values[$Attributes[$Value]][ | ];
	]
```
With the following enum definition
```
public enum Foos
    {
        [EnumMember(Value = "BAR")]
        Bar,

        [EnumMember(Value = "WIDGET")]
        Widget,
        
        [EnumMember(Value = "FOOBAR")]
        FoorBar
    }
```
The resulting typescript is
```
export type Foos = Value = "BAR" | Value = "WIDGET" | Value = "FOOBAR";
```

I am looking to get
```
export type Foos = "BAR" | "WIDGET" | "FOOBAR";
```

Am I just missing some syntax from the Typewriter definition?

**Comment by frhagn** [comment]
Hi @thegreatco,

In Typewriter templates enum values are just strings so you'll have to define a method to extract the part of the value you're intrerested in e.g.
```
${
    string ExtractedValue(Attribute attribute)
    {
        var index = attribute.Value.IndexOf("=");
        return attribute.Value.Substring(index + 1).Trim();
    }
}
$Enums(PingMeSharp.Model.*)[
    export type $Name = $Values[$Attributes[$ExtractedValue]][ | ];
]
```
