### ISSUE TITLE
how can i exclude namespace from conversion?

### ISSUE THREAD

**Issue by aj92singh** [frhagn/Typewriter#160]
Whenever i convert my namespace is coming as a module . I want to exclude namespace from conversion. Is there any way to exclude ?

model.tst :
module App {
    $Classes(*Model)[
    export class $Name {
    
    
        $Properties[
        // 
        
        public $name: $Type = $Type[$Default];
        ]
    }]
}

EmpModel.cs:

namespace App.Models
{
    public class EmpModel
    {
        public int id { get; set; }
        public string name { get; set; }
        public string DOB { get; set; }
    }
}

Generated TS:

module App.Models {
    export class EmpModel {
    
    
        
        // 
        
        public id: number = 0;
        
        // 
        
        public name: string = null;
        
        // 
        
        public dob: string = null;
        
    }
}

Desired Output:
 export class EmpModel {
    
    
        
        // 
        
        public id: number = 0;
        
        // 
        
        public name: string = null;
        
        // 
        
        public dob: string = null;
        
    }

**Comment by frhagn** [comment]
Hi @aj92singh,
You can try using a template without defining a module e.g.

```
${
    using Typewriter.Extensions.Types;
}
$Classes(*Model)[
export class $Name {
    $Properties[
    public $name: $Type = $Type[$Default];]
}]
```

**Comment by aj92singh** [comment]
Thanks it worked.

**Comment by aj92singh** [comment]
just one Question:

If i define a class and initialize it in asp.net controller and give it some values. Then is it possible to access those value in angular component via Type Writer generated ts file.

**Comment by frhagn** [comment]
Check out http://frhagn.github.io/Typewriter/pages/examples.html for info on how you can generate Angular Services to access server-side API:s
