### ISSUE TITLE
Only class own's properties are available

### ISSUE THREAD

**Issue by jaenyph** [frhagn/Typewriter#161]
When using $Class $Properties only the properties defined on the class are available, not all the properties in the hierarchy.

**Comment by frhagn** [comment]
Hi @jaenyph,
You can access properties from bas classes by using $BaseClass e.g.

```
$Classes(...)[
    $Properties[...]
    $BaseClass[
        $Properties[...]
   ]
]
```

**Comment by patrykbuzowicz** [comment]
I used this piece of code to traverse the entire hierarchy:
`    IEnumerable<Property> GetPropertiesFromEntireInheritanceHierarchy(Class c)
    {
        var properties = new List<Property>();

        while (c != null)
        {
            properties.AddRange(c.Properties);
            c = c.BaseClass;
        }

        return properties;
    }

    interface $Name { $GetPropertiesFromEntireInheritanceHierarchy[...]
    }]`

**Comment by k-vekos** [comment]
@patrykbuzowicz Where do I put the `GetPropertiesFromEntireInheritanceHierarchy` function?

**Comment by patrykbuzowicz** [comment]
I found no better way than to place it in the .tst file. I would love to reuse .tst code though across multiple projects

**Comment by frhagn** [comment]
@k-vekos, see https://frhagn.github.io/Typewriter/pages/getting-started.html#custom-methods for info om how to use custom methods in your templates
