### ISSUE TITLE
Parameters in the Url are not encoded

### ISSUE THREAD

**Issue by cwoolum** [frhagn/Typewriter#172]
I ran into an issue where a user was typing a value into an input that was becoming a parameter for a RESTful Url. 

An example route for this is ```/tasks/{myTaskId}```. The issue becomes if the user types a url with a ```/``` slash in it. The $Url function should encodeURIComponent any parameters passed into it.

https://github.com/frhagn/Typewriter/blob/84e3625a2a4ba188a16b0707c8e7dc4605b49ab3/src/CodeModel/Extensions/WebApi/UrlExtensions.cs#L141

I can submit a PR if it is agreed that this should be the intended functionality.

**Comment by frhagn** [comment]
Fixed in 1.12.0

**Comment by enriko-riba** [comment]
This breaks my existing codebase :-(

This script:
```
$Methods[
    public static Url_$Name = ($Parameters(p => p.Type.IsPrimitive)[$Name: $Type][, ]) => baseUrl + `$Url`;
    ] 
```
generates the following output:
```
public static Url_GetPdfById = (id: number) => baseUrl + `api/xyz-pdf/${encodeURIComponent(id)}`;
```

> Argument of type 'number' is not assignable to parameter of type 'string'.	

as a quick solution the parameter enclosed by encodeURIComponent should be cast to any

**Comment by ronbrogan** [comment]
@enriko-riba Our team just ran in to the same problem. Upgrading to 1.12.2 fixed it for us.
