### ISSUE TITLE
Visual Sutdio 2017 Add New Item doesn't show TypeScript Template

### ISSUE THREAD

**Issue by laurentkempe** [frhagn/Typewriter#185]
I have installed the plugin on Visual Studio 2017 and I see it installed but when I try to add a TypeScript Template into my ASP.NET Core project I don't see the file proposed in the Add New Item dialog

![image](https://cloud.githubusercontent.com/assets/272612/25555218/822dad20-2ce0-11e7-81dc-7d49423b9d7a.png)

I tried on a ASP.NET MVC web application and it is the same.

I also tried by adding a file trough the file system, but then nothing happens while adding Models.

Any idea?

**Comment by wheelibin** [comment]
I also have this problem, but I found you can actually just create the file manually (for example by creating a typescript file and renaming it to .tst) and everything seems to work.

**Comment by laurentkempe** [comment]
Thanks @wheelibin I tried that before posting but it doesn't work for me

**Comment by frhagn** [comment]
Fixed in 1.12.0
