### ISSUE TITLE
add support for using generics when using $Type

### ISSUE THREAD

**Issue by johannordin** [frhagn/Typewriter#19]
`public MyGenericClass<int>` should give `MyGenericClass<int>` when using `$Type`

`public List<MyGenericClass<int>>` should give `MyGenericClass<int>[]` when using `$Type`

`public class MyGenericClass<T> {
   private T genericProperty
}` should give `T` when using `$Type` for the property.

**Comment by johannordin** [comment]
solved with pending pull request

**Comment by frhagn** [comment]
resolved with PR #24
