### ISSUE TITLE
VS Pro 2017 v15.2 (26430.16 release) error when running Typewriter - not implemented

### ISSUE THREAD

**Issue by GoranBlazevic** [frhagn/Typewriter#195]
When trying to render any template, I get the following error in Visual Studio:

Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))

Am I missing a component of some sort?

**Comment by aschwartz-satcom** [comment]
maybe a dupe of this?
https://github.com/frhagn/Typewriter/issues/168

**Comment by GoranBlazevic** [comment]
Holy smeg, yes it is, that's the thing - unloaded projects in solution cause Typewriter to fail.

Thank you @aschwartz-satcom
