### ISSUE TITLE
Encoding number parameters in Url 

### ISSUE THREAD

**Issue by mikolus** [frhagn/Typewriter#197]
Fix for #172  adds call to the encodeURIComponent for url parameters even when the parameter is number, but that method only takes string. I guess it should check for the type of the parameter.

**Comment by frhagn** [comment]
Hi @mikolus, sorry about that!
I've published a new version (1.12.1) that should resolve this issue, could you please confirm? Thanks

**Comment by mikolus** [comment]
Perfect, it works great, thanks a lot!
