### ISSUE TITLE
Encoding parameters in Url

### ISSUE THREAD

**Issue by enriko-riba** [frhagn/Typewriter#199]
The changes introduced by #197 and #172 have an issue if the url parameter is strongly typed.
Please see my example in #172.

Could you add a cast as any in the emitted code?
e.g.` /${encodeURIComponent(id as any)`

**Comment by frhagn** [comment]
Hi @enriko-riba, 
what version are you using? This issue was (hopefully) fixed in 1.12.2

**Comment by enriko-riba** [comment]
Yes, sorry, wasn't using 12.2.
The emitted TS code is correct with the latest version:
`public static Url_GetPdfById = (id: number) => baseUrl + `api/xyz-pdf/${id}`;`
