### ISSUE TITLE
Web API extensions for ASP.NET Core 2.0

### ISSUE THREAD

**Issue by miguel1603** [frhagn/Typewriter#201]
Apparently the api extension is not working well when mapping the url

```C#
[Route("api/[controller]")]
public class UserController : Controller
{
     [HttpGet]
     [Route("GetUserName")]
     public string GetUserName(){
          return "miguel";
     }
}
```

Correct route above would be `api/user/GetUserName`
Current `GetUserName`

**Comment by Marcel1024** [comment]
this is solved in #191

**Comment by francipvb** [comment]
What about mixed [Http{Get|Post|Delete}] routes?

they doesn't work well with WebAPI extensions with ASP.Net Core.

Cheers,

**Comment by francipvb** [comment]
Test this:
```c#
        // SampleDataController.cs
        [HttpGet("[action]")]
        public IEnumerable<WeatherForecast> WeatherForecasts()
        {
            return null; // just for testing
        }
```

with this:

```
    // $HttpMethod $Url
```

This is the result:

```
// get api/sampleData/
```

Expected is this:

```
// get api/sampleData/weatherForecasts
```

Cheers,

**Comment by Marcel1024** [comment]
thats strange. are you sure you are using version 1.13.0? 
I've added some unit tests supporting your case.. see above.

am i missing something?
