### ISSUE TITLE
TypeWriter does not render tst after update visual studio to 15.3

### ISSUE THREAD

**Issue by alirezapooneh** [frhagn/Typewriter#204]
I installed last version of TypeWriter in Visual studio 15.2. Rendering tst files was done successfully. But after update VS to 15.3, rendering tst files do not generate ts files or update them. Also when right click on tst file and select Render Template.

**Comment by Sc0tTyXL** [comment]
Just tested is in one of my solutions but seems to work as expected.

Deleted all generated filed and used Render Template to get them back.

VT15.3, TS2.3 and .NET Framework 4.6 ASP.NET MVC

**Comment by frhagn** [comment]
Hi @alirezapooneh, 
everything seems to be working fine for me so maybe the issue is related to something specific in your setup.
Could you provide som more details of the problem like project type, target framework etc. and also check if there's any info in the output window under 'Typewriter' after you try o render a template, thanks.

**Comment by alirezapooneh** [comment]
I create new empty web project and try again by first sample tst template on github. but only show "Rendering completed" on my status bar and no file geneated.
Output window does not show any log and has no item to select TypeWriter (in from section or output window)

VS 15.3, TS 2.3,  .NET Framework 4.6 ASP.NET MVC;

Also I download source code and compile ad run all tests, 8 test failed!

**Comment by alirezapooneh** [comment]
see it:
[https://1drv.ms/i/s!AhGEtzvFCKT5nlcMaWvSDVBAKoLK](url)

**Comment by alirezapooneh** [comment]
Hi @frhagn 
Can I enable Log mode or Debug mode in rendering to find problem?!
I repair VS 2017, uninstall TypeWriter and install again, reset VS settings and other solutions, But could not solve the problem.
Please help! My project is in last step is blocked! ;(

**Comment by frhagn** [comment]
Hi @alirezapooneh, 
You can try to open your solution in the experimental instance of Visual Studio while debugging Typewriter. To enable debugging you'll need to change a couple of properties on the Typewriter project e.g. set start action to "Start external program" with the path "C:\Program Files (x86)\Microsoft Visual Studio\2017\<Your edition>\Common7\IDE\devenv.exe" and add "/RootSuffix Exp" to the command line arguments. A good place to start setting break points is in GenerationController.cs
