### ISSUE TITLE
How to post ajax data in body rather than url

### ISSUE THREAD

**Issue by gregveres** [frhagn/Typewriter#206]
Hi @frhagn 

I use typewriter to create Typescript interface files for my REST api. I have a C# base class that all my API controllers derive from so I use that as the trigger in typewriter.  Here is my current .tst definition:

```
$Classes(:OurBaseApiController)[
    export class $ServiceName {
        $Methods[
        // $HttpMethod: $Url
        public static Route$Name = ($Parameters(p => p.Type.IsPrimitive)[$Name: $QualifiedType][, ]) => `/$Url`;
        public static $name($Parameters[$Name: $QualifiedType][, ]): JQueryPromise<$ReturnType> {
            return $.ajax({
                url: $ParentServiceName.Route$Name($Parameters(p => p.Type.IsPrimitive)[$Name][, ]),
                type: '$HttpMethod',
                data: $RequestData
            });
        }]
    ]
}
```

but this puts all the post parameters into the URL and that gets big and messy some times. I would like to put the data into the body of a post. To do that I need to add a dataType: 'json' value into the ajax config and I need to run the $RequestData through JSON.stringify().

I would like to do an "if" on the $HttpMethod. If $HttpMethod == POST, then I want to do inject these things, otherwise I want to leave it as is above. 

How would I go about doing that? 

I have thought about making a function that takes $HttpMethod as an argument and returning a string dataType: 'json' or returning an empty string. I think that would work for setting dataType, but I am not sure how to handle the $RequestData portion. 

Any suggestions?
Thanks

**Comment by gregveres** [comment]
Thanks @Marcel1024. 

I see that you are using a predicate expression to limit the method selections. Thats good. I will see if I can work with that to select a different template based on $HttpMethod.

I am always curious to see how others do things. So I have a couple of questions about why you are approaching it the way you do, if you don't mind...

why do you have the ajax methods in an io class? given that it is protected, I assume you are always deriving another class off of the $ServiceName class and it is that derived class that the rest of your code uses. 

I am just exposing the $ServiceName class and I put the methods on the $ServiceName class as public members. So I have something like this when I want to use it:

`import { ClubsService } from 'Api/ClubController'`
and then when I use it:
`ClubsService.AddMember(...).done(...).fail(...)`

Also I see that you are using different templates based on $RequestData being null or not. I don't do that so in my case I end up outputting data: null and it seems to work. I see that when you already know that $RequestData is null, you don't output the data:null. Are you doing that to keep the outputted code size as small as possible?

I see you are also explicitly outputting cache: false for Gets. Have you run into a problem where the browser was caching those results? I am not putting cache: false and I don't seem to be running into that problem. But maybe i am just getting lucky or maybe my users are running into and I don't know. 

Thank you for sharing this is really helpful.

**Comment by Marcel1024** [comment]
Hi Greg,

I don't know if the way i do it is a good way. whatever works for you should be ok. 
The way with the io property is just conveniënt for our projectmembers so they'll know it was generated and its splitted with their (javascript) controller code.

For the cache part..yes, we were having some troubles with a grid where data was updated on an other machine. Edge would return cached data so those changed would not show up.

**Comment by gregveres** [comment]
Thanks Marcel.

**Comment by gregveres** [comment]
Thanks to Marcel, I have typewriter generating posts with the data in the body. For anyone looking at the code, I first wondered why Marcel had checks for requestData being null as part of the lambda expression. It turns out you need that to select the proper form of the ajax call when there are no arguments.
