### ISSUE TITLE
Binary type

### ISSUE THREAD

**Issue by chifret** [frhagn/Typewriter#207]
Hi,

When rendering the classes, the c# variable type "Binary" keeps on staying Binary in Typescript.
`        public virtual Binary  myVar { get; set; }`
becomes :
`        public myVar: Binary = null;`

Couldn't that be a problem , because of this :
> As in JavaScript, all numbers in TypeScript are floating point values. These floating point numbers get the type number. In addition to hexadecimal and decimal literals, TypeScript also supports binary and octal literals introduced in ECMAScript 2015.
> 
> ```
> let decimal: number = 6;
> let hex: number = 0xf00d;
> **let binary: number = 0b1010;**
> let octal: number = 0o744;
> ```
(https://www.typescriptlang.org/docs/handbook/basic-types.html)

Thanks in advance for your support !

**Comment by Marcel1024** [comment]
Not sure i understand..

Binary is not a C# primitive. Meaning...Binary is probably a self made c# class object in your sample.
Therefore Typewriter will also return the type name Binary.

I think you mean this:

`
public virtual byte[] myVar { get; set;}
`

with the current codebase, this will render as:

`public myVar: number[];`

which is correct typescript as you stated in your post.
