### ISSUE TITLE
Add support for ASP.NET vNext applications

### ISSUE THREAD

**Issue by frhagn** [frhagn/Typewriter#21]
Changes in the project structure in Visual Studio breaks the file nesting and metadata features required by Typewriter for vNext projects.

**Comment by cwoolum** [comment]
I think there is also an issue related to the way dependencies are referenced as well. I can't seem to generate anything for referenced vNext class libraries. Should this be a separate issue?

**Comment by frhagn** [comment]
Duplicate of #76
