### ISSUE TITLE
List of all attributes

### ISSUE THREAD

**Issue by bandersen22000** [frhagn/Typewriter#211]
Hi

I have the following C# model, that I convert to a TS clsss. But for each property I would like to have a method that returns all the attributes, for the current property. Is this possible ? 

I would suggest making a list of attributes classes. But I don´t know how to append $Properties[$Attributes[FullName: $FullName;Name: $Name;Value: $Value;]] to a list or if it is possible ?

The  C# model looks like this:
`    public class CaseModel : BaseObject
    {
        [Description("SagsId")]
        public string CaseId { get; set; }

        [StringLength(2000, ErrorMessage = "Kommentar: Max 2000 karaktere er tilladt")]
        [Description("Kommentar")]
        [MaxLength(2000)]
        public string Comment { get; set; }

    }`
Best regards
Benjamin Andersen

**Comment by frhagn** [comment]
Hi @bandersen22000,
try something like this:

```
${
    string ParsedValue(Attribute attribute)
    {
        // Todo: Parse the attribute value properly
        if(int.TryParse(attribute.Value, out var value))
            return attribute.Value;

        return $"\"{attribute.Value.Replace("\"", "\\\"")}\"";
    }
}
$Classes(*Model)[
export class $Name {
    $Properties[
        public $name: $Type;    
        public AttributesFor$Name = () => [ $Attributes[{ name: "$Name", value: $ParsedValue }][, ] ];
    ]
}
```

**Comment by bandersen22000** [comment]
Thanks.

I ended up using the following:
`export class $Name {
$Properties[    
    // $LoudName
    public $Name: $Type = $Type[$Default];
    
    $Name_attributes() {
        var attributes = new AttributeModel();
        attributes.Description = "$GetDescription";
        attributes.StringLength = $GetStringLength;
        attributes.IsRequired = $IsRequired;
        attributes.Name = "$Parent.$Name";
        return attributes;

    } 

    ]
   }]`
This gives med the following output from:
C#
`  [Required]
        [Description("Oprettelses dato")]
        public DateTime CreatedDate { get; set; }`
Output:
`    // CREATEDDATE
    public CreatedDate: Date = new Date(0);
    
    CreatedDate_attributes() {
        var attributes = new AttributeModel();
        attributes.Description = "Oprettelses dato";
        attributes.StringLength = null;
        attributes.IsRequired = true;
        attributes.Name = "AliasModel.CreatedDate";
        return attributes;

    } `
