### ISSUE TITLE
If output file is deleted, it is not automatically regerated

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [frhagn/Typewriter#212]
When a typewriter enabled project is opened missing TS files are not automatically generated.  We must right click on each missing file and select "Render Template".

Is their a setting that will force regeneration if the file is missing?

Also, is their any way to force regeneration of all the files?  We have found that changes are not automatically detected and to be safe we must regenerate all the files (one at a time).

We're using VS2017 (15.3.3) and VS2015 (update 3).

Our templates all resemble:

${
    using Typewriter.Extensions.Types;

    Template(Settings settings)
    {
        settings.IncludeCurrentProject();
        settings.IncludeReferencedProjects();
        settings.IncludeProject("Project.Services");
        settings.OutputExtension = ".ts";

        settings.OutputFilenameFactory = file =>
        {
            return $"Project.Services.NotificationStrings.ts";
        };
    }
}

// File is autogenerated, do not edit
$Enums(Project.Services.NotificationStrings)[
enum $Name {
    $Values[
    $Name = $Value][,]
}

export { $Name as default, $Name };
]

Thanks for this wonderful tool!

**Comment by rvalimaki** [comment]
For regenerating all the files we are using the trick of saving the template file. You can for example add an empty row to the end of that file, then delete that row and then hit the save, and all your files (for that template) will be regenerated. (We happen to have several different template files for different purposes, so we need to repeat this trick for every template when needed.)

Exactly same procedure can be used for single files to be generated: just open them, add an empty line, delete that line and save.

Please note that the option to regenerate files upon saving the template needs to be ticket in the Typewriter settings.

For us the regenerating of files upon saving individual .cs files has been very reliable, so we are forcing the regeneration for all files only about once in a month just to be sure that nothing has slipped through.

**Comment by Michael-Tajmajer-Emrsn** [comment]
This is fine for a few templates -- we have about 30 now, and will continue to add more.  Opening and saving 30 templates is not a valid use case for us :-(

I posted a PR that adds a "regerate all" to the context menu -- we're using that version of Typewriter until it may be merged.

**Comment by frhagn** [comment]
PR released in 1.14.0

**Comment by DanteNirav** [comment]
Hey guys,

Any update on this? or code snippet for regenerating all files.

My Problem is :- 

I have a base class which gets updated, and the changes in the base class is not getting ported in the derived classes.

Thanks for helping out
