### ISSUE TITLE
Support for IsAbstract in Method

### ISSUE THREAD

**Issue by msawczyn** [frhagn/Typewriter#215]
Thanks for adding $IsAbstract to Class ... it would be extremely useful to have it in Method as well. 

My use case is that I'm generating translations for service classes, and the services inherit from a base class. The base class has been abstract alI along, but I just ran across a need to add an abstract method there and implement in the derived services. Generating the TS, I'm getting two implementations in each service, and I can't see a way of filtering out the abstract declaration in the base class to solve the problem.

Of course, if this gets implemented, might as well add it to Property while you're there :-)

If too time consuming, I can dig into it and create a pull request when I get it solved, but no guarantees on schedule.

Thanks.

**Comment by frhagn** [comment]
Hi @msawczyn,
I've added this in Typewriter 1.14.0.
