### ISSUE TITLE
DocComments only works when saving the .tst file

### ISSUE THREAD

**Issue by thesmallbang** [frhagn/Typewriter#217]
my config 

`
namespace MyNamespaceTypes { $Classes(A.Namespace*Model)[
	/** $DocComment  */
	export interface $Name { $Properties[
	 /** $DocComment  */ 
		$name: $Type;]
	}]
}
`

If I open a model and save the changes the .ts file is generated without comments
If i open the .tst file and save changes the .ts file generated contains the comments as expected

**Comment by frhagn** [comment]
Hi @thesmallbang,
that's wierd.. I've tried your code snippet om my machine and it renders the comments both when saving the cs-file and the template..

Are you running the latest version of Typwriter (1.14.0)?

**Comment by thesmallbang** [comment]
Sorry once i had my workaround i moved on and forgot to follow up. I will test again tomorrow and update this issue.

**Comment by thesmallbang** [comment]
I still plan to review the issue and provide feedback.

**Comment by rjamesnw** [comment]
Is `$DocComment` still valid?  It doesn't seem to work anymore.

**Comment by rjamesnw** [comment]
Ok, figured this out.  The OP was using a CUSTOM extension method, like this:

 ```
${
   string DocComment(Class c)
    {
      var comment = c?.DocComment?.ToString() ?? "";
      return string.IsNullOrWhiteSpace(comment) ? "" : "\r\n/** "+comment+" */";
    }

    string DocComment(Property p)
    {
      var comment = p?.DocComment?.ToString() ?? "";
      return string.IsNullOrWhiteSpace(comment) ? "" : "\r\n/** "+comment+" */";
    }
}
```

...

```
import { NgModule } from '@angular/core';

$Classes([Table])[@NgModule()$DocComment
export class $Name {
    $Properties[$DocComment
      public $name: $Type = $Type[$Default];
    ]
}
export interface I$Name extends $Name {}
]
```

The overloads are needed to capture the different types in the class and property scopes.
