### ISSUE TITLE
1.14.0 VSIX won't install in VS 2017 Pro, previous versions work fine.

### ISSUE THREAD

**Issue by rbatka** [frhagn/Typewriter#219]
I get the following error when trying to install Typewriter in a freshly installed VS2017 Professional, both through the extensions browser inside VS and from the releases here on github. It seems to be an issue only affecting the latest release, 1.14.0.

I went and grabbed the previous release (1.13.0) and it installed fine.

Thought you might want to know.

![image](https://user-images.githubusercontent.com/198500/31284349-489d6126-aa86-11e7-9db3-06834f9e07cf.png)

**Comment by frhagn** [comment]
Hi @rbatka 
Thanks for pointing this out. What specific version of Visual Studio are you running? E.g. 15.x.y

**Comment by rickbatka** [comment]
VS version is 15.0.0-RTW+26228.4
Typescript version I have installed is is 2.1.5.0 (if that matters)

**Comment by frhagn** [comment]
Hi @rbatka,
I just published a new release (1.14.1) that hopefully will resolve this issue.
It would be great if you could verify that it works..
Thanks!

**Comment by rickbatka** [comment]
That fixed it! 

Thanks again for the awesome plugin.
