### ISSUE TITLE
Optional type

### ISSUE THREAD

**Issue by dodyg** [frhagn/Typewriter#22]
Is there anyway to generate typescript definition with optional type? This is especially important when trying to generate typescript interfaces automatically

**Comment by frhagn** [comment]
Hi @dodyg, could you please provide some more details about this? An example would be nice.

**Comment by dodyg** [comment]
How can I generate

```
interface Person {
  Name? : string
  Age? : string
}
```

**Comment by frhagn** [comment]
If you want it on all properties, just add the question mark in the template like this:
```typescript
$Classes(*Models*)[
interface $Name { $Properties[
    $Name?: $Type;]
}]
```
Otherwise the problem is how to determine which properties should be decorated. One solution is to use attributes to mark optional properties in your c# classes e.g:
```typescript
${
    var IsOptional = (Property p) => p.Attributes.Any(a => a.Name == "Optional");
}
$Classes(*Models*)[
interface $Name { $Properties[
    $Name$IsOptional[?]: $Type;]
}]
```

```csharp
public class Person
{
    [Optional]
    public string Name { get; set; }
    public int Age { get; set; }
}
```

**Comment by dodyg** [comment]
This is exactly what I need. Thank you so much. I just created a dummy Optional attribute and tag the necessary properties with it

```
[AttributeUsage(AttributeTargets.All)]
public class OptionalAttribute : Attribute
{
}
```
