### ISSUE TITLE
Type.BaseClass vs base "Type"

### ISSUE THREAD

**Issue by michaelaird** [frhagn/Typewriter#221]
I'm trying to write some code that will iterate through Types and yield return Types. I'm running into a roadblock when I need to deal with the base class of a Type because BaseClass is a Class instead of a Type.

Is there a way to convert from a Class to a Type or would it be possible to add a property to Type for BaseType that returns a Type?

**Comment by frhagn** [comment]
Added support in Typewriter 1.15.0 for casting Class, Enum and Interface to Type e.g.
```
${
    string Test(Class c)
    {
        var baseType = (Type)c.BaseClass;
        return baseType?.Name;
    }
}
$Classes(FILTER)[
    $Test
]
```

**Comment by michaelaird** [comment]
This perfectly solves my need. Thank you!
