### ISSUE TITLE
Type.Default() does not correctly detect collections or dictionaries

### ISSUE THREAD

**Issue by joelving** [frhagn/Typewriter#223]
Type.Default() renders "null" for IList<T>, List<T>, and IEnumerable<T> rather than "[]" as expected. Changing to T[] works as expected.
Dictionary<T1, T2> renders "null" instead of "{}" as expected.

Tested on .Net Core 2.0, Visual Studio Community 17, v. 15.3.5, with Typewriter 1.14.2.

**Comment by frhagn** [comment]
Hi @joelving,
thats wierd, I just tested this on my machine with the same setup as you describe and it works as expected. Could you provide a sample of your template and c# source file? Thanks
