### ISSUE TITLE
[FR]: Substitute 'any' for properties of unknown type

### ISSUE THREAD

**Issue by joelving** [frhagn/Typewriter#224]
**Feature request**: It would be useful to render complex types, which aren't themselves rendered by Typewriter, could be rendered as 'any', since it will not compile in its current form.

Example:
`public IList<UserLoginInfo> CurrentLogins { get; set; }`
Might render as
`currentLogins: UserLoginInfo[]`
But since UserLoginInfo isn't rendered it doesn't compile. An alternative would be to render it as
`currentLogins: any[]`

**Comment by michaelaird** [comment]
For us, this wouldn't make sense. We sometimes render the method in one template and the dependencies (DTOs) in a separate template. I don't think the templates know anything about the types that other templates might have rendered  (or will in the future).

**Comment by frhagn** [comment]
Hi @joelving,
@michaelaird is correct, the templates doesn't know what types have been generates so this isn't possible to implement..

However, if you don't want to generate certain types you can use a custom method in your template e.g.
```
${
    string CustomType(Property property)
    {
        if(property.Type.Name == "UserLoginInfo[]")
            return "any[]";
        return property.Type.Name;
    }
}
$Classes(FILTER)[
export class $Name { $Properties[
    public $name: $CustomType;]
}]
```
