### ISSUE TITLE
Work for Inner Classes and Include Base Classes

### ISSUE THREAD

**Issue by RandyBuchholz** [frhagn/Typewriter#226]
I have two items here, that can be broken out.
I'm playing with Razor Pages and embedding View Models inside them. The ViewModels inherit from a reference model. I have a "TypeWriter" attribute to trigger generation.
```
// Reference Model
  public class Person {
      [Display(Name="Name")]
      public string Name { get; set; }
      public int Age { get; set; }
  }

// Inside Razor Page
  public class IndexModel : PageModel {
      [TypeWriter]
      public class LocalPerson : Person {
          [Display(Name = "Local Name")]
          public new string Name { get => base.Name; set => base.Name= value; }
      }
      
      public LocalPerson ViewPerson { get; set; } 
  }
```
The class LocalPerson is not generated from inside IndexModel. If I move it out on its own, it generates, but only the local property (Message), and not Age.

Ideally, this would generate either a stand-alone ts class for LocalPerson, or both classes.
```
    export class LocalPerson {
        public name: string = "";
        public age: int = 0;
    }
```

**Comment by frhagn** [comment]
Hi @RandyBuchholz,
Typewriter only works on top level classes so in order to render nested classes you'll need to change the template to something like this:
```
$Classes[$NestedClasses("[TypeWriter]")[
    export class $Name {
// Properties from class
$Properties[
        public $name: $Type;] 
// Properties from base class (if any)
$BaseClass[$Properties[
        public $name: $Type;]]
    }
]]
```
