### ISSUE TITLE
Typewriter doesn't work with project type "Website"

### ISSUE THREAD

**Issue by marxxxx** [frhagn/Typewriter#229]
Hi,

is this a known issue or something that can be changed?
Typewriter doesn't seem to do anything when the project type is a website instead of a web application.

Thank you!

Kind regards
Markus

**Comment by michaelaird** [comment]
Website projects don't have a  *.*proj file and aren't represented as real projects to Visual Studio. TypeWriter relies on that project representation to add output files from the template to the current project.

**Comment by michaelaird** [comment]
I haven't tried it but, the most recent release that includes the option to not add files to the project might now work with website project types.
