### ISSUE TITLE
ValueTuple not recognized

### ISSUE THREAD

**Issue by mskovacic** [frhagn/Typewriter#231]
C# ValueTuple type is neither recognized in tst file nor Typewriter output.

input C# file:
```
[GenerateAsTypeScriptClass]
public class MyDTO
{
    public (string a, string b) P { get; set; }
}
```

generated TypeScript with default tst file:
```
class MyDTO {
    public p: 
}
```

When I change the tst file into
```
${
    using Typewriter.Extensions.Types;
    string TypeMap2(Property property)
    {
        var type = property.Type;
        return type.FullName+ ";";
    }
}

$Classes([GenerateAsTypeScriptClass])[
    class $Name {
        $Properties[public $name: $TypeMap2][;
        ]
    }
]
```

I get that ValueTuple isn't recognized even in the tst file, with the following output:
```
class MyDTO {
    public p: System.;
}
```

**Comment by frhagn** [comment]
1.16.0 adds support for rendering ValueTuples in vs 2017, but it's still not possible to use them in Typewriter templates...

The output is an anonymous object, e.g.
`public (string a, int b) MyTuple { get; set, }`
will render
`MyTuple: { a: string, b: number };`

**Comment by jeeshenlee** [comment]
I'm getting TupleValue in my generated TS file and fix it by overwriting it. 

![TupleValue](https://user-images.githubusercontent.com/1011777/88359252-894bd380-cda4-11ea-9fc7-b36fec3665c0.jpg)
