### ISSUE TITLE
Handling date parameter for angular service

### ISSUE THREAD

**Issue by mailivore** [frhagn/Typewriter#238]
Hi,

I am using this template to generate my service calls : 
`public $name($Parameters[$name: $TypeConverter][, ]) : angular.IPromise<$ReturnType> {
            
            return this.CustomHttpService.request<$ReturnType>({
                url: `$Url` , 
                method: "$HttpMethod", 
                data: $RequestData
            });
        };]`

It outputs this function : 
`public getByDateArrete(dateArrete: Date) : angular.IPromise<Resultat[]> {
            
            return this.CustomHttpService.request<Resultat[]>({
                url: `api/Resultat/GetByDateArrete?dateArrete=${dateArrete}` , 
                method: "get", 
                data: null
            });
        };`

It is not working because the date is passed as an object in the request.

Is there a way to customize the $url parameter to output "dateArrete.toISOString()" instead of "dateArrete"?

Thanks.

**Comment by frhagn** [comment]
Hi @mailivore,

There's no built-in way of doing this, but you can use a custom method, e.g.

```
${
    using Typewriter.Extensions.WebApi;

    string CustomUrl(Method method)
    {
        var url = method.Url();
        var dates = method.Parameters.Where(p => p.Type.IsDate);

        foreach(var date in dates)
        {
            url = url.Replace($"${{{date.Name}}}", $"${{{date.Name}.toISOString()}}");
        }

        return url;
    }
}
...
    public $name($Parameters[$name: $TypeConverter][, ]) : angular.IPromise<$ReturnType> {
        return this.CustomHttpService.request<$ReturnType>({
            url: `$CustomUrl` , 
            method: "$HttpMethod", 
            data: $RequestData
        });
    };]
...
```

**Comment by msawczyn** [comment]
Hi @mailivore,

The problem is incoming dates rather than outgoing dates, since ASP.NET binding handles Date => DateTime, but no JSON package (to my knowledge) handles DateTime => Date. JSON.Net (the serialization most everyone uses) sends DateTime across as an ISO8601 string, so it's a fairly good assumption.

What I've been doing is an enhancement on something I saw an an answer to a javascript question on, I believe, StackOverflow (I wish I had commented the URL or could find it again ... if I do, I'll update this post for the richly deserved attribution). This doesn't do any preprocessing in the template, but rather handles it at runtime in the TypeScript.

The trick is to pass every result of an ajax call through a TypeScript routine that recursively checks to see if a piece is a complex object and, if so, whether any of its properties matches the regex for an ISO 8601 date string. If there's a match, replace it with a Date based on that the string and keep going until you've exhausted all the properties.

*(Note that I'm also generating async/await code. It isn't pertinent to the question but I thought I'd throw it in on the off-chance someone reading this isn't aware that, in current TypeScript flavors, it's available.)

```typescript
$Classes(Some.Namespace.*)[
   export class $ServiceName {

      private static iso8601RegEx: RegExp = /(19|20|21)\d\d([-/.])(0[1-9]|1[012])\2(0[1-9]|[12][0-9]|3[01])T(\d\d)([:/.])(\d\d)([:/.])(\d\d)/;

      protected fixDates(input: any) {
         if (typeof input === "object") {

            for (let key in input) {
               if (!input.hasOwnProperty(key))
                  continue;

               const value = input[key];
               const type = typeof value;

               if (type === "string" && value.match($ServiceName.iso8601RegEx)) {
                  input[key] = new Date(value);
               } else if (type === "object") {
                  this.fixDates(value);
               }
            }
         }

         return input;
      }

      $Methods[
      public async $name($Parameters[$name: $TypeConverter][, ]) : angular.IPromise<$ReturnType> {
         let response = await this.CustomHttpService.request<$ReturnType>({
            url: `$CustomUrl` , 
            method: "$HttpMethod", 
            data: $RequestData
         });
         let result: $ReturnType = <$ReturnType>(this.fixDates(response.data));
         return result;
      }
      ]
   }
}
```

**Comment by mailivore** [comment]
Searched for the same exact problem and found this issue which I forgot that I was the author.

frhagn your solution works perfectly thank you.

msawczyn I already had a solution for incoming dates.
I have a converter class which is registered at the startup of my angular app so I don't have to bother if my service has not been generated by typewriter.

Here is the code: 
```
Export class DateConverterConfig {
     
        public static $inject = [
            "$httpProvider"
        ];

        private navigation: any;

        constructor(
            $httpProvider: angular.IHttpService
        ) {
            function convertToDates(input) {
                
                for (var key in input) {
                    if (!input.hasOwnProperty(key)) continue;

                    if (typeof input[key] === "object") {
                        convertToDates(input[key]);
                    } else {
                        if (typeof input[key] === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(.\d{1,3})?Z?/.test(input[key])) {
                            var date: string = input[key];
                            input[key] = new Date(input[key]);
                            //input[key] = moment.tz(date, "Europe/Paris").toDate();

                        }
                    }
                }
            }

            $httpProvider.defaults.transformResponse.push((responseData: any) => {
                convertToDates(responseData);
                return responseData;
            });
        }
    }
```

And to register it :
```
angular
    .module('MyApp', ['libs'])
    .config(DateConverterConfig)
```

**Comment by Ironpython-studio-enoch** [comment]
> Searched for the same exact problem and found this issue which I forgot that I was the author.
> 
> frhagn your solution works perfectly thank you.
> 
> msawczyn I already had a solution for incoming dates. I have a converter class which is registered at the startup of my angular app so I don't have to bother if my service has not been generated by typewriter.
> 
> Here is the code:
> 
> ```
> Export class DateConverterConfig {
>      
>         public static $inject = [
>             "$httpProvider"
>         ];
> 
>         private navigation: any;
> 
>         constructor(
>             $httpProvider: angular.IHttpService
>         ) {
>             function convertToDates(input) {
>                 
>                 for (var key in input) {
>                     if (!input.hasOwnProperty(key)) continue;
> 
>                     if (typeof input[key] === "object") {
>                         convertToDates(input[key]);
>                     } else {
>                         if (typeof input[key] === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(.\d{1,3})?Z?/.test(input[key])) {
>                             var date: string = input[key];
>                             input[key] = new Date(input[key]);
>                             //input[key] = moment.tz(date, "Europe/Paris").toDate();
> 
>                         }
>                     }
>                 }
>             }
> 
>             $httpProvider.defaults.transformResponse.push((responseData: any) => {
>                 convertToDates(responseData);
>                 return responseData;
>             });
>         }
>     }
> ```
> 
> And to register it :
> 
> ```
> angular
>     .module('MyApp', ['libs'])
>     .config(DateConverterConfig)
> ```





https://typescripts.space/questions/what-is-the-best-way-to-send-a-search-parameter-to-a-url

**Comment by AdaskoTheBeAsT** [comment]
you can use <drums> 
https://github.com/AdaskoTheBeAsT/date-interceptors
https://www.npmjs.com/package/@adaskothebeast/angular-date-http-interceptor
