### ISSUE TITLE
How can i include multiple projects via Settings.IncludeProject() ?

### ISSUE THREAD

**Issue by marxxxx** [frhagn/Typewriter#239]
Hi,

i would like to restrict the projects used for type generation and therefore explicitly specify them using settings.IncludeProject(). However i can't figure out how to specify multipe projects in a call to IncludeProject() ?
Is there any way to achive this? 

Thank you very much!

Kind regards
Markus

**Comment by frhagn** [comment]
Hi @marxxxx,
Just call `AddProject` multiple times e.g.
```
settings.AddProject("ProjectA")
    .AddProject("ProjectB")
    .AddProject("ProjectC");
```

**Comment by marxxxx** [comment]
Great, thanks!! @frhagn
