### ISSUE TITLE
Can't get the default value for Type

### ISSUE THREAD

**Issue by jeeshenlee** [frhagn/Typewriter#244]
Tried to get the default value of the Type but can't seems to be able to do it. $Default is not available in the intellisense.

`        constructor() { $Properties[
            this.$Name = this.$Type[//Default value of type];]
        }
`

![typewriter-01](https://user-images.githubusercontent.com/1011777/34067052-ec4019ac-e255-11e7-99c9-a48374ada9ce.jpg)

**Comment by frhagn** [comment]
Hi @jeeshenlee,

$Default is an extension method so you'll need to include the `Typewriter.Extensions.Types` namespace. e.g.
```
${
    using Typewriter.Extensions.Types;
}
...
$Properties[
    this.$Name = this.$Type[$Default];
]
...
```
