### ISSUE TITLE
Render from another non-referenced project in same solution

### ISSUE THREAD

**Issue by RGVGreatCoder** [frhagn/Typewriter#245]
I have a Visual Studio 2017 Solution made of a Web API back-end project (ASP.Net Cor 2.0) and a front-end project (Angular 5, Bootstrap). This solution runs fine without having to set the front-end project to reference the back-end project (there is no need to). These two projects run on separate websites in my IIS 10.0 Web Server.
Having installed Typewriter on the front-end project, how do I configure the Typewriter template (or any other configuration file) to read the models and controllers in the back-end project and be rendered in a folder in the front-end project? :)

**Comment by frhagn** [comment]
Hi @RGVGreatCoder,
As long as the projects are in the same solution you can include the back-end project in the template constructor. e.g.

```
${
    Template(Settings settings)
    {
        settings.IncludeProject("BackEndProject");
    }
}
$Classes(...)[
...
]
```

**Comment by RGVGreatCoder** [comment]
Thank you frhagn. I will try this next year. By the way. Happy New Year!
