### ISSUE TITLE
Allow some kind of cache for a single run

### ISSUE THREAD

**Issue by KeithHenry** [frhagn/Typewriter#248]
I have TS models that are built by TypeWriter if I decorate their C#. They can reference each other, and when they do I want to add an ES6 `import` to the file.

The problem is that the same type can occur multiple times on different properties.

So my C# might look like:

```c#
// a.cs
[MyAttribute]
public class A {
    public string Simple { get; set; }
}
```

```c#
// b.cs
[MyAttribute]
public class B {
    public A Foo { get; set; }
    public A Bar { get; set; }
}
```

And I want my TypeWriter output to look like:
```TypeScript
// a.model.d.ts
export default interface A {
    simple: string;
}
```

```TypeScript
// b.model.d.ts
import A from './a.model'; // This should only appear ONCE
export default interface B {
    foo: A;
    bar: A;
}
```

My TypeWriter `tst` code looks something like this:

```c#
${
    ...
    static HashSet<string> imported = new HashSet<string>();

    bool NeedsImport(string typeName, string className = null) {
        // Primitive
        if(typeName == "string" ||
            typeName == "number"||
            typeName == "boolean"||
            typeName == "Date"||
            typeName == "Array")
            return false;

        // Generic
        if(typeName == "T")
            return false;

        // Union
        if(typeName.Contains("|"))
            return false;

        // Object
        if(typeName.StartsWith("{"))
            return false;

        // Already imported   
        if(!string.IsNullOrEmpty(className) && imported.Contains($"{className}+{typeName}"))
            return false;

        return true;
    }

    string Imports(string memberName, string typeName, string className) {
        if(typeName.EndsWith("[]")) {
            typeName = JsonType(typeName.Substring(0, typeName.Length - 2));
            if(!NeedsImport(typeName, className))
                return null;

            memberName = typeName;
        }

        imported.Add($"{className}+{typeName}");

        return $@"
import {memberName} from './{typeName}.model'; /* {className}+{typeName} */";
    }

    string Imports(Property p) {
        
        string className = p.Parent.ToString();
        string defaultMemberName = p.Type;
        string typeName = JsonType(p);

        if(!NeedsImport(typeName, className))
            return null;

        return Imports(defaultMemberName, typeName, className);
    }
}
$Classes([MyAttribute])[$Properties[$Imports]]
$Classes([MyAttribute])[
    ... rest of template
]
```

This works fine on a "Render All Templates" run, but in general use (so edit a C# model class, then edit it again) the `static HashSet<string> imported` persists.

I want to ask: _in this run have I already imported this model to this output?_

There are a number of ways this could be done:

* An instance of something that persists for a run
* An instance of something for a single file/class in a run
* A way to reset static properties between runs 

Alternatively is there a way to check whether a type's model has already been imported to a file in TypeWriter already?

**Comment by Beej126** [comment]
The outermost scope of a template runs at file scope ... do your imports logic at that level, via function that takes File vs Propery, keeping lookup dictionary/hash at that level to know what’s already been done... iterate down into all classes and properties from there ... I pasted imports sample code on a previous comment

**Comment by KeithHenry** [comment]
@Beej126 cheers, but what do you mean by _File vs Property_? I think #247 is working on a similar problem but looks like quite a different approach - I don't want to enumerate attributes, I want to dedupe the types of properties.

**Comment by KeithHenry** [comment]
That works great, thanks.
