### ISSUE TITLE
WebApi / DTO Proxy generator for C#

### ISSUE THREAD

**Issue by kbalint** [frhagn/Typewriter#259]
Hi, I've successfully created a C# version from the TypeScript WebApi generator.
Everything is OK (enums/DTO-s, controllers generating as expected), but one thing has an error:

        // $HttpMethod: $Url
        public virtual async Task<$ReturnType> $Name($Parameters[$FullName $Name][,]) {
       ...
       }

In this part, instead of the $FullName parameter, which is My.CustomNamespace.MyObject I'd like to get only the "MyObject" part, because the DTO's namespace will be ProxyNameSpace.MyObject. In the TypeScript version this does not cause any errors, because there i can use $Type, and it will be OK.
I would need a $OriginalCLRTypeName variable here, because $Type is overwritten with the TypeScript typename.

I've written a custom C# extension function for replacing the NS, but I can't fit in: `$Parameters[$MyExtensionFunction($FullName)...]` 
is not working.

Do you have any hints how to resolve it without forking? Thanks!

**Comment by frhagn** [comment]
Hi @kbalint, 
try something like this: `$Parameters[$Type[$OriginalName] $Name][,]`

**Comment by kbalint** [comment]
Hi @frhagn, thanks for the quick answer! I think this will not work, because for example:

$FullName = System.Collections.Generic.List<My.CustomNamespace.CustomObject>
$Type[$OriginalName] = List

so still I'd need to inject a function to replace the FullName's namespace somehow. :)

**Comment by kbalint** [comment]
OK, solved!
I've added a new request object, which is a single type, so $OriginalName will work with it fine, and
added a property to it which is the List<>.  Thanks!
