### ISSUE TITLE
Wrong method type when method name has a name 'Delete'

### ISSUE THREAD

**Issue by MNie** [frhagn/Typewriter#262]
I Have controller like this:

```csharp
[RoutePrefix("a")]
public class AController : Controller {
    [Route("delete")]
    public bool Delete(){...}
}
```

and template like this:

```typescript
export class $Name {
    constructor(private callService: CallService) {
    } $Methods[
        
    public $Name= ($Parameters[$name: $Type][, ]): Observable<$Type> => {
        return this.callService.$HttpMethod(`$Url`, $RequestData);
    }]
}]
```

I expect to get a result like this:

```typescript
...
public save = (): Observable<bool> => {
        return this.callService.get(`a/delete`, null);
}
...
```

but I get:

```typescript
...
public save = (): Observable<bool> => {
        return this.callService.delete(`a/delete`, null);
}
...
```

So it seems that `$HttpMethod` resolve incorrectly default HttpGet if a method has a name `Delete`/route `Delete`, is it expected behavior?

**Comment by MNie** [comment]
@agustinbcu01 I don't know if your comment is an answer or something, cause you don't provide any answer/additional info. Regardless of that, I thought that default verb for not explicitly marked action in a controller is always a `HttpGet` but it seems that [it isn't](https://stackoverflow.com/a/44897831/2947860)

I will close an issue.

**Comment by agustinbcu01** [comment]
there are some http commands 
get, post, put, delete, ...
if you named the method ass the http command. you not need to decorate, they match it, and us standard. In other hand if the method  name is difference and you don't use a decorator, default is Get.
