### ISSUE TITLE
Getting actual Type of an Enumerable

### ISSUE THREAD

**Issue by Sc0tTyXL** [frhagn/Typewriter#264]
Hi there,

There is an issue when handling a Enumerable property, for example:
`public List<SomeType> SomeProperty { get; set; } = new List<SomeType>();`

You cannot get BaseClass for the Type of SomeProperty as it is null.
The problem it that the **Type** for an Enumerable property is **SomeType[]** and not **SomeType**.

I assume that nobody needs the **SomeType[]** and uses a string replace to remove the brackets to get the typename. And in case you want to check if something is an Enumerabe it is better to use the IsEnumerable property is anyway.

It would be great if the value of the Type property can be changed to the actual SomeType Type or another property is added to get this value (to avoid braking changes, though option 1 would be better long term).

This is probably the source issue for #256 

Sc0tTy

**Comment by agustinbcu01** [comment]
you need to ask is   type.IsGeneric || t.IsEnumerable 
and iterate on type.TypeArgument.    foreach(var subtypes in type.TypeArguments)
The generic type can contain multiple types and also can be nested.

**Comment by Sc0tTyXL** [comment]
Sorry for the very late response, but this is the fix/code I needed!
Issue can be closed.
