### ISSUE TITLE
How to run on build server

### ISSUE THREAD

**Issue by bender2k14** [frhagn/Typewriter#277]
It is possible to run Typewriter as a build step in a build definition on a build server?  I specifically care about doing this with TFS.

Naturally, Typewriter is automatically run _if_ the extension is installed in Visual Studio.  I am in a scenario where there are many developers on a project but only a few of them have Typewriter installed.  I would like to add a build step to our build definition that runs Typewriter in order to ensure that any changes made in C# but not (automatically) copied to the TypeScript are not breaking changes.

**Comment by agustinbcu01** [comment]
There a discussion on #133 and #196
