### ISSUE TITLE
If a type is an array of T, how can I get the T type from it?

### ISSUE THREAD

**Issue by luizfbicalho** [frhagn/Typewriter#279]
I have a property C[]
if I call a Method

` IEnumerable<Property> Subform(Class clas)
    {
           return clas.Properties.Where(prop=> prop.Attributes.Any(x=>x.FullName.Contains("SubForm")));
    }`

if the type is an Array how can I get the type of the C class?

**Comment by werddomain** [comment]
Same isue here, i wish to know if it's an array of primitive or if it's an array of complex class
