### ISSUE TITLE
Support for visual studio 2019

### ISSUE THREAD

**Issue by NullMDR** [frhagn/Typewriter#286]
Currently this extension couldn't be installed in vs 2019.

**Comment by Christian-Schiffer** [comment]
I am very interested in that too, as it turns out vs 2019 is fully usable, I tried installing Typewriter now, with the refresh version since NullMDR had tried it with the fist preview and failed, I hoped that might have changed since. Unfortunately, no joy. @frhagn first of all, thank you so much for such a great tool, amazing job and I can't wait to see your 2.0 version up and running. To the meat of the matter, do you have any plans of adding support to vs 2019 anytime soon or are you focusing on your 2.0 version?

**Comment by NullMDR** [comment]
I've tried to build this extension with vs2019 and, with no luck, a lot of test failed. As this extension 
 heavily depends on EnvDTE I'm afraid there will be a lot of works to do for compatibility.

**Comment by mike-ward** [comment]
Submitted pull request #292 to update the manifest to VS 2019.

I built an [updated version for VS 2019](https://github.com/mike-ward/Typewriter/releases/tag/v1.20.1). Works on my machine 😄

**Comment by NullMDR** [comment]
> Submitted pull request #292 to update the manifest to VS 2019.
> 
> I built an [updated version for VS 2019](https://github.com/mike-ward/Typewriter/releases/tag/v1.20.1). Works on my machine 😄

After installing I got
> Visual Studio has detected one or more extensions that are at risk of not functioning in a future VS update.

Seems like there are really some compatibility issue.

**Comment by mike-ward** [comment]
Didn't see that when I installed. I wonder if it is dependent on what extensions are installed?

Anyways, this is just a bridge until the author comes out with his new version. Looking forward to it.

**Comment by michaelaird** [comment]
> > Submitted pull request #292 to update the manifest to VS 2019.
> > I built an [updated version for VS 2019](https://github.com/mike-ward/Typewriter/releases/tag/v1.20.1). Works on my machine 😄
> 
> After installing I got
> 
> > Visual Studio has detected one or more extensions that are at risk of not functioning in a future VS update.
> 
> Seems like there are really some compatibility issue.

VS 2019 requires async extensions. https://blogs.msdn.microsoft.com/visualstudio/2018/05/16/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/

**Comment by Christian-Schiffer** [comment]
> Submitted pull request #292 to update the manifest to VS 2019.
> 
> I built an [updated version for VS 2019](https://github.com/mike-ward/Typewriter/releases/tag/v1.20.1). Works on my machine 😄

I tried it on my machine, it works just fine, thanks, great job!

**Comment by kevin-david** [comment]
FYI, the next version of VS 2019 will completely refuse to load this extension:

![image](https://user-images.githubusercontent.com/1923186/55444551-de971c80-5584-11e9-93ef-877e691893d6.png)

**Comment by info-lvsys** [comment]
Works on VS2019 but throws a "this is using deprecated APIs!" warning.

**Comment by mike-ward** [comment]
Weird, I'm not seeing errors

![image](https://user-images.githubusercontent.com/567927/55742633-217e4780-59fe-11e9-967e-858e0e2fbe2f.png)

**Comment by kevin-david** [comment]
I should have been more clear - "next version" being 2019.1 (at least the pre-release version available to me as of 4/2), not the just-released 2019, which I think just outputs warnings.

**Comment by Gambero81** [comment]
@frhagn do you have some news about this issue?

**Comment by Gambero81** [comment]
it seem the extension need to update the ExtensionPackage class (`Typewriter/VisualStudio/ExtensionPackage.cs) changing inheritance from Package to AsyncPackage.cs`)

see https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration

**Comment by madskristensen** [comment]
For this to be compatible with VS2019 version 16.1 (currently in public preview), you need to migrate to use AsyncPackage with background load. This is supported in VS2015 and above and is described here https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration

**Comment by michaelaird** [comment]
@frhagn are these cases being closed because they won't be implemented? or because they've been fixed somewhere else?

**Comment by antur84** [comment]
> @frhagn are these cases being closed because they won't be implemented? or because they've been fixed somewhere else?

It's been fixed in the latest release, it's not available from the VS marketplace yet (download link is dead there for some reason), but you can get it manually from the release page. https://github.com/frhagn/Typewriter/releases/tag/v1.22.0

**Comment by frhagn** [comment]
@michaelaird sorry about that.. It's fixed in 1.22.0. Anyone else (besides @antur84) having trouble downloading it from the VS Marketplace?.. seems to be working for me.

**Comment by michaelaird** [comment]
Thanks! 1.22 updated fine for me directly in VS.

**Comment by anarchitect** [comment]
Download link didn't download the proper version for me either
