### ISSUE TITLE
Wrong Property.Type.IsGeneric value in case of primitive[] array

### ISSUE THREAD

**Issue by buchatsky** [frhagn/Typewriter#345]
**Description**
.IsGeneric returns 'false' for primitive[] array types of properties (but correctly returns 'true' for Object[] array props).
C# class:
```
   public partial class Category
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; } = null!;
        public string? Description { get; set; }
        public byte[]? Picture { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
```
For 'Picture' property (incorrect): 
`type: number[], isEnum: True, isGeneric: False, unwrapType: number[], isUnwrapPrimitive: False, firstTypeArg: number;`

For 'Products' property (correct): 
`type: Product[], isEnum: True, isGeneric: True, unwrapType: Product, isUnwrapPrimitive: False, firstTypeArg: Product;`

**Desired behaviour**
For 'Picture' property: 
type: number[], isEnum: True, **isGeneric: True, unwrapType: number, isUnwrapPrimitive: True**, firstTypeArg: number;

**Versions**
Typewriter64: 2.5.0  ( [@adaskothebeast](https://github.com/AdaskoTheBeAsT) 's clone )
Visual Studio:  2022 (17.0.4)

**Comment by NeVeSpl** [comment]
.IsGeneric applies to C# type, not Typescript type. Arrays in C# are not generic type.
```
(byte[]?).IsGeneric == false
(Product[]?).IsGeneric == false
(ICollection<byte>).IsGeneric == true
(ICollection<Product>).IsGeneric == true
```
Typewriter has many bugs, but this is not one of them.

**Comment by buchatsky** [comment]
But property.Type.Name returns "number[]", not "byte[]". So I thought it was applied to Typescript

**Comment by NeVeSpl** [comment]
Yeah, it is a mess, you never know in Typewriter if you work with C# or TS type. It is why in [NTypewriter](https://github.com/NeVeSpl/NTypewriter) there is a clear separation, code model is pure c# and TS functionality is available only through built-in functions.
