### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by dodyg** [frhagn/Typewriter#36]
Does Typewriter support inheritance? 

```
public class Report {}

public class SpecificReport : Report {}
```

**Comment by frhagn** [comment]
Yes, in the current version you can use ```$BasClass``` e.g.
```TypeScript
$Classes(...)[
class $Name extends $BaseClass[$Name] {

}]
```
I'm currently working on better support for inheritance, nested types and generics for the upcoming 1.0 release :)

**Comment by dodyg** [comment]
Awesome

**Comment by cmorgado** [comment]
using 
$Classes(...)[
class $Name extends $BaseClass[$Name] {

}]
works fine if my class inherits another class .. however 
If the class doesn't has a base class it generates :

export class MyNormalClass **extends **{

**Comment by coolkev** [comment]
Put a code block at the top of your template
```
${

	string ClassNameWithExtends(Class c) {
        return c.Name +  (c.BaseClass!=null ?  " extends " + c.BaseClass.Name : "");
    }


}

```

Then you can call it like so:

```
$Classes(...)[
class $ClassNameWithExtends {

}]
```

**Comment by cmorgado** [comment]
Nice.. I even added another function to add the imports!

`${

    Template(Settings settings)
    {
        settings
            .IncludeCurrentProject()
            .IncludeProject("eCommerce.Models")
            ;
    }

    string Inherit(Class c)
    {
    if (c.BaseClass!=null)
        return "extends " + c.BaseClass.ToString();
      else
         return  "";
    }
    
    string Imports(Class c){
   
      return  (c.BaseClass!=null) ? ( "import {" + c.BaseClass.ToString() +"} from \"./" + c.BaseClass.ToString() +"\";") :"";
     
    }



    // import {ProductItemInStore} from "./ProductItemInStore";
}

//from external
$Classes(eCommerce.Models.*)[
$Imports

export class $Name$TypeParameters $Inherit { $Properties[
    $Name: $Type;]

 

constructor( $Properties[
    $name: $Type ][,]){
    $Properties[
        this.$Name=$name;]
    }
   
}]`

**Comment by cmorgado** [comment]
Now I just need to figure how to set the imports when my C# class has "complex" objects:

` public class ProductItemDetails : ProductItemInStore
    {

      
        public IEnumerable<ImageDetail> ImagesDetails { get; set; }

        public IEnumerable<AggregatorTuple> Aggregators { get; set; }
    }`

**Comment by sogundu** [comment]
Based on this:  https://github.com/frhagn/Typewriter/issues/75

```javascript
${
    using Typewriter.Extensions.Types;

    Type[] CalculatedModelTypes(Class c)
    {
        return c.Properties
            .Where(p => !p.Type.IsPrimitive || p.Type.IsEnum)
            .Select(p => p.Type).ToArray();
    }
}

$Classes(Project.Models.*)[
    $CalculatedModelTypes[
        import {$ClassName} from './$ClassName';]

    export class $Name { $Properties[
        $name: $Type;] 
    }
]
````

**Comment by aluanhaddad** [comment]
@cmorgado Take the types of all the properties, extended interfaces and classes, and implemented interfaces and so on put them into a single collection projecting to a simple type woth properties for the exported type name and the import path and then do `.Distinct()`.

**Comment by sigVince** [comment]
Here's how to import all needed references (for complex objects and inheritance)
`    string Inherit(Class c)
    {
    if (c.BaseClass!=null)
        return " extends " + c.BaseClass.ToString();
      else
         return  "";
    }

string Imports(Class c){
      List<string> neededImports = c.Properties
        .Where(p => !p.Type.IsPrimitive)
        .Select(p => "import { " + p.Type.ToString() + " } from './" + p.Type.ToString() + "';").ToList();
      if (c.BaseClass != null) { 
        neededImports.Add("import { " + c.BaseClass.ToString() +" } from './" + c.BaseClass.ToString() + "';");
      }
      return String.Join("\n", neededImports.Distinct());
    }`

`$Classes(*DTO)[$Imports

export interface $Name$Inherit {

$Properties[    $name: $Type;
]}
]`

**Comment by w0ns88** [comment]
@sigVince your answer is great, however, on my side when I try it, I get the following error:
"Cannot convert type char to string" on the c.Properties

Any idea why?

**Comment by Belaroth** [comment]
Here's how to get a distinct list of properties for the class and it's base
`    string propertiesWithBase(Class c) {
    
        List<string> neededImports = c.Properties
	        .Select(p => "public " + p.name + ": " + p.Type.Name).ToList();
        if (c.BaseClass != null) { 
	        neededImports.AddRange(c.BaseClass.Properties
	        .Select(p => "public " + p.name + ": " + p.Type.Name));
        }

        return string.Join(", ", neededImports.Distinct());
    }`
