### ISSUE TITLE
Enable 'Smart indenting' for *.tst

### ISSUE THREAD

**Issue by frhagn** [frhagn/Typewriter#4]

**Comment by LeeCheneler** [comment]
This would be a help, along with smart new lines.

 It isn't immediately clear that this will put all methods on the same line:
 `$Methods[$name: ($Parameters[$name: $Type][, ]) => $Type;]`

And this will put them on new lines:
` $Methods[

$name: ($Parameters[$name: $Type][, ]) => $Type;]`

Sorry about the poor formatting... Can't get a single new line to work in the Markdown for some reason.
