### ISSUE TITLE
Reserved word C# @... syntax needs @ removed

### ISSUE THREAD

**Issue by jonstelly** [frhagn/Typewriter#42]
If you have a C# method with a parameter that starts with a @ to use a reserved word:

    void ProcessEvent(SomeEvent @event) { ... }

The @ sign needs to be removed for $Name, etc...

**Comment by frhagn** [comment]
Hi @jonstelly

I'll look into that. Meanwhile you could use a custom method to solve this issue, e.g.
${
    var SafeName = (Parameter p) => p.Name.Trim('@');
}

And then use $SafeName instead of $Name in your template.

**Comment by frhagn** [comment]
Moving this to 1.1

**Comment by frhagn** [comment]
Resolved i Typewriter 1.1
