### ISSUE TITLE
Add support for events and delegates

### ISSUE THREAD

**Issue by randre70** [frhagn/Typewriter#47]
Please add the full support for all declaration types including events and delegates.
Currently, I use TypeWriter to generate a custom websocket wrapper which is able at the javascript side to invoke methods on the server (exposed using typewriter) and to listen to events raised at the server end and invoke subscriber functions (handwriten but could be exposed by typewriter as well).

Thanks so much for a perfectly working extension.

**Comment by frhagn** [comment]
Hi @randre70 I'll look into that.
If possible, it would be great if you could post an example of the code you're using.

**Comment by randre70** [comment]
Thanks a lot, I can't wait to test this and will provide an example if possible. I'm supposed to be on holidays for 3 weeks from next wednesday ;)
