### ISSUE TITLE
Delete unmodified files when saving a template

### ISSUE THREAD

**Issue by frhagn** [frhagn/Typewriter#5]

**Comment by JonasSamuelsson** [comment]
is this something that will be done in the near future?

**Comment by frhagn** [comment]
It requires some major changes to the rendering infrastructure so it probably won't be fixed for a while. For now you'll have to delete out-of-sync files manually, sorry.

Is this a big issue for you?

**Comment by JonasSamuelsson** [comment]
It would be nice to have but no, it's not a big issue.
