### ISSUE TITLE
Add support for creating TypeScript JSX

### ISSUE THREAD

**Issue by johannordin** [frhagn/Typewriter#55]
With TypeScript 1.6 knocking on the door (already in beta), typescript has support for React's JSX-syntax via .tsx-files. 

[ts 1.6](http://blogs.msdn.com/b/typescript/archive/2015/09/02/announcing-typescript-1-6-beta-react-jsx-better-error-checking-and-more.aspx) 
[issue on typescript](https://github.com/Microsoft/TypeScript/pull/3564)

**Comment by frhagn** [comment]
@johannordin great idea!

**Comment by frhagn** [comment]
Moved to #60
