### ISSUE TITLE
Some of the templates are not working

### ISSUE THREAD

**Issue by cwoolum** [frhagn/Typewriter#59]
I tried using the angular and model templates and some of the helpers don't seem to be working. 

I'm not seeing any references to `$rootnamespace$` in the code.

**Comment by frhagn** [comment]
Hi @cwoolum,
What version of Typewriter are you using? The item templates in for angular and models in the source repo are outdated at the moment. Fixing them are on my todo list, but there are some other things that needs work first...

Check out http://frhagn.github.io/Typewriter/pages/examples.html for some more current usage examples, there you can also find an angular example.

Hope this works out for you!

**Comment by cwoolum** [comment]
Hey Fredrik, I'm using the newest version but digging through the code, I
found those templates. I liked them because they generated the automated
module names. It seems like the old templates provided a lot more features.

**Comment by frhagn** [comment]
I see... I'm afraid `$rootnamespace$` is just a standard placeholder in Visual Studio item templates that is replaced by a calculated namespace when the template is added to the project. So it's not a Typewriter property.

Other than that the features provided by the WebApi extensions on the examples page (`$Url`, `$HttpMethod` and `$RequestData`) are very similar to the angular item template. Take a look under https://github.com/frhagn/Typewriter/tree/master/src/CodeModel/Extensions/WebApi

**Comment by cwoolum** [comment]
Aah, I see. I'll take a look at using reflection to get the namespaces of the classes.

**Comment by frhagn** [comment]
If you're just interested in the namespaces of the classes there's a `$Namespace` property you can use.

**Comment by cwoolum** [comment]
So I ended up just inverting the template slightly and it worked for me.

```
$Classes(*Model)[ 
   module $Namespace {  
    export interface $Name { $Properties[
        $name: $Type;]
    }
   }
]
```

**Comment by frhagn** [comment]
Cool, nice one!
