### ISSUE TITLE
Cannot use custom method in $Parameters collection

### ISSUE THREAD

**Issue by cwoolum** [frhagn/Typewriter#62]
I'm trying to use a custom method in $parameters but for some reason it is not getting converted.

```
$Parameters[$name: $CalculatedType][, ]
```

My method signature is ```string CalculatedType(Type m)```. Is this the wrong signature?

**Comment by frhagn** [comment]
Since the custom method is called from within a $Parameters scope the method signature must be `string CalculatedType(Parameter p)` (in the method you can use `p.Type` to get the type)

**Comment by cwoolum** [comment]
That worked! Thanks!

**Comment by harishrathi** [comment]
@frhagn I have created SO tag http://stackoverflow.com/questions/tagged/typewriter
