### ISSUE TITLE
Add support for OData Controllers

### ISSUE THREAD

**Issue by philcarbone** [frhagn/Typewriter#64]

**Comment by frhagn** [comment]
Hi @philcarbone,
Could you please provide som more info on this issue?

**Comment by philcarbone** [comment]
Sorry for the vagueness. I was thinking that using a OData controller as an input for a "template" would be really powerful too. Since OData controllers have an assigned entity, it would be really powerful to have TS files generated to match the exposed entities. Or even better, read an OData feed and produce the TS objects that match that feed. 

I know this could be done via naming convention too (on the C# side not the feed side)... I just thought it would make things really convenient for people that already have code that a convention may not match.

I am starting an Open Source project with another individual to make a library for writing OData queries in TS with types flowing though the entire fluent interface and we are looking at options to generate our TS objects to match their C# equivalents. 

https://github.com/andyjmay/TypeScriptedOData

**Comment by frhagn** [comment]
I see. You can use Typewriter with any C# class so OData Controllers are already supported.
Using an OData feed to produce TypeScript classes is not supported, and I think that's a bit outside the scope of this extension.
