### ISSUE TITLE
Steps to contributing

### ISSUE THREAD

**Issue by cwoolum** [frhagn/Typewriter#66]
I was wondering if there is any sort of documentation or some sort of information/tutorials on creating a Roslyn plugin like this? I would definitely be interested in contributing but I have no idea where to start.

**Comment by frhagn** [comment]
Hi Chris,
Cool, any help is appreciated!
I've been meaning to write some kind of contributing guide, but I haven't got around to it yet.

Here are some links to help you get started:
https://github.com/madskristensen
https://www.visualstudio.com/en-us/integrate/explore/explore-vside-vsi.aspx
https://msdn.microsoft.com/en-us/library/dd885118.aspx
https://github.com/dotnet/roslyn/wiki/Samples-and-Walkthroughs
