### ISSUE TITLE
No generation for public neasted class

### ISSUE THREAD

**Issue by Gambero81** [frhagn/Typewriter#69]
Hi, i'm using TypeWriter to generate ts files from cs class, now i have this class:

    public static partial class SmartUtils
    {
        public class TestModel
        {
            public string Test { get; set; }
        }
    }

and i cannot find a way to generate ts of TestModel class...
i tried this template but dont work...

    $Classes(TestModel)[
    export class $Name {
        $Properties[
        //$LoudName
        public $Name: $Type;]
    }]

do you have any suggestion?
thanks

**Comment by frhagn** [comment]
Hi @Gambero81, 
You can access nested classes via the `$NestedClasses` property e.g.
```
$Classes(SmartUtils)[$NestedClasses[        
export class $Name {
    $Properties[    
    public $Name: $Type;]
}]]
```

**Comment by Gambero81** [comment]
hi, thanks for your reply, i tested your template and it's work only if my class in inside a namespace,
i have some classes declared without namespace and in this case no code is generated, there is a solution to handle translation of classes who not have namespace?
Thanks

**Comment by Gambero81** [comment]
1. if a class is declared without namespace, no ts file is generated

**Comment by Gambero81** [comment]
2. suppose to have this 2 files in the project:

File1.cs:
   namespace Utils
   {
      public static partial class SmartUtils
      {
         public class NestedClass1
         {
            public string Property1 { get; set; }
         }
      }
   }

File2.cs:
   namespace Utils
   {
      public static partial class SmartUtils
      {
         public class NestedClass2
         {
            public string Property2 { get; set; }
         }
      }
   }

and this typescript template:
   $Classes(SmartUtils)[$NestedClasses(NestedClass1)[
   module SmartUtils
   { 
      export class $Name
       {$Properties[
          public $name: $Type;]
       }
   }]]

in this situation the output would be:
File1.ts: 
   module SmartUtils
   { 
       export class NestedClass1
       {
           public Property1: string;
       }
   }

but the output is generated also for File2 so the result is:

File1.ts: 
   module SmartUtils
   { 
       export class NestedClass1
       {
           public Property1: string;
       }
   }

File2.ts: 
   module SmartUtils
   { 
       export class NestedClass1
       {
           public Property1: string;
       }
   }

**Comment by frhagn** [comment]
Filters are independent from each other, but I agree that this behaviour is bad in this case. 
You could try something like this instead:
```
$Classes[$NestedClasses(nc => nc.BaseClass.Name == "SmartUtils" && nc.Name == "NestedClass1")[
module SmartUtils
{ 
    export class $Name
    {$Properties[
        public $name: $Type;]
    }
}]]
```

**Comment by Gambero81** [comment]
Hi @frhagn this template seem to work:

    $Classes[$NestedClasses(nc => nc.ContainingClass != null && nc.ContainingClass.Name ==    "SmartUtils" && nc.Name == "NestedClass1")[
    module ObjectModel
    {
        export class $Name 
        {$Properties[
            public $Name: $Type;]
        }
    }]]

but the problem now is that i have some classes without namespace, in this case there is no ts generation and no errors in Typewriter output window, how to handle classes without namespace?
Thanks

**Comment by frhagn** [comment]
Hi @Gambero81,
I'm afraid there's no workaround for this at the moment. Typewriter requires a namespace to find classes in the source files, and it's unaware of partial classes.

I'll look into implementing support for both of theese issues.

**Comment by Gambero81** [comment]
Thanks @frhagn, if you can, write on this issue when you will fix this problems so i can i notice the changes and update my Typewriter version

**Comment by frhagn** [comment]
Hi @Gambero81,
I've added support for source files without namespace in Typewriter 1.3.
I still haven't foud a good solution to the partial class issue, so for now you'll have to manually add a filter that matches only one of the partials to get the proper behaviour e.g.

```
$Classes[$NestedClasses(nc => nc.ContainingClass != null 
    && nc.ContainingClass.Name == "SmartUtils" 
    && ((File)nc.ContainingClass.Parent).Name != "File2.cs"
    && nc.Name == "NestedClass1")[
module SmartUtils
{
    export class $Name 
    {$Properties[
        public $Name: $Type;]
    }
}]]
```

**Comment by Gambero81** [comment]
Hi @frhagn , thanks for your reply, glad to know TypeWriter updates!
I'm still searching for a solution for partial classes, i tried your code but without success:
In particular the filter:

    ((File)nc.ContainingClass.Parent).Name != "File2.cs"

throw an error 

    "Error rendering template. Cannot apply filter to identifier 'NestedClasses'."

so i replaced with:

    nc.ContainingClass.Parent.GetType() == typeof(File)
    && ((File)nc.ContainingClass.Parent).Name != "File2.cs"

with this additional statement the template does not throw errors but no ts files is generated

seem who nc.ContainingClass.Parent is not a File class because test only for type of nc.ContainingClass.Parent does not generate ts files.

Who to retrieve the File class?
Thanks

**Comment by frhagn** [comment]
It's probably a null reference issue, try something like this: `((File)nc.ContainingClass?.Parent)?.Name != "File2.cs"`.

**Comment by Gambero81** [comment]
Hi @frhagn, unfortunately seem not a null reference issue,
using     ((File)nc.ContainingClass?.Parent)?.Name != "File2.cs"    the error still remain.

to verify the value of nc.ContainingClass.Parent i create this example:

    ${
            string PrintContaingClassParent(Class c)
            {
                  return c.ContainingClass.Parent.ToString();
            }
      }

    $Classes[$NestedClasses(nc => nc.ContainingClass != null 
                        && nc.ContainingClass.Name == "SmartUtils" 
                        && nc.Name == "NestedClass1" 
                        && nc.ContainingClass.Parent != null 
                       )[
    module ObjectModel
    {
        $PrintContaingClassParent
        export class $Name
        {$Properties[
            public $Name: $Type;]
        }
    }]]

the value generated from $PrintContaingClassParent is "NestedClass1"
so nc.ContainingClass.Parent is not a File object.

you can reproduce the issue with the above code sample (https://github.com/frhagn/Typewriter/issues/69#issuecomment-163580435)
using file1.cs and file2.cs

i'm doing something wrong?
Thanks

**Comment by frhagn** [comment]
What I meant to write was `((nc.Parent as Class)?.Parent as File)?.Name != "File2.cs"`, sorry
This way you should be able to filter out File2.cs from the rendered results

**Comment by Gambero81** [comment]
@frhagn you're great!! thank you very much for support in this issue, you solved a very big task!! 
I finally full integrated Typewriter in my project!

looking for new features of this beautiful library! (I especially would like comment generation for properties copied from server comments)

**Comment by Gambero81** [comment]
@frhagn you're great!! thank you very much for support in this issue, you solved a very big task!! 
I finally full integrated Typewriter in my project!

looking for new features of this beautiful library! (I especially would like comment generation for properties copied from server comments)

**Comment by frhagn** [comment]
Thanks @Gambero81!
