### ISSUE TITLE
Suggestion: add support for comments

### ISSUE THREAD

**Issue by Gambero81** [frhagn/Typewriter#70]
It would be great to add support for copy comments from server side cs class / interface / methods / properties to client generated typescript files!

**Comment by frhagn** [comment]
Hi @Gambero81,
Great idea! I'll look into that.

**Comment by moleschott** [comment]
Any development for this issue?

**Comment by frhagn** [comment]
Basic support added in Typewriter 1.5

**Comment by Gambero81** [comment]
How does it work? i cannot find documentation... can you provide a sample?
Thanks

**Comment by frhagn** [comment]
Hi @Gambero81,
`$Classes`, `$Methods` etc. now have a `$DocComment` property, try something like this to get started:
```
...
$Methods[
    $DocComment[
    // $Summary
    // $Returns $Parameters[
    // $Name: $Description]]
    ...
]
...
```
