### ISSUE TITLE
when using .. in Template constructor  to output files to another folder, a .. folder is created in the project inside VS

### ISSUE THREAD

**Issue by stombeur** [frhagn/Typewriter#71]
unfortunately, when I deleted that folder in my project in VS, a fewof my folders and files on disk were deleted and I just lost half a days work.

That's not your fault of course, but it's probably something that needs to be looked at

repro:

in the Template constructor do like this:

```
Template(Settings settings)
    {
        settings.IncludeCurrentProject();
        settings.OutputFilenameFactory = file => "../otherproject/wwwroot/js/" + file.Name + ".ts";
    }
```

the result is that you will get new folders in your project called .. etc
if you right click that folder ".." in solution explorer, instead of deleting it from the project, VS will try to delete it from disk.

**Comment by stombeur** [comment]
what I was trying to do is to output the generated files in another location on disk.
Also, when in the Template constructor you do like this:

```
Template(Settings settings)
    {
        settings.IncludeCurrentProject();
        settings.OutputFilenameFactory = file => "c:\\temp\\" + file.Name + ".ts";
    }
```

the .tst file becomes invalid somehow and cannot be parsed anymore. But that's probably another, unrelated issue.

**Comment by frhagn** [comment]
Hi @stombeur,
Saving rendered files in other folders isn't supported. Each template keeps track of it's generated files by looking at it's own child nodes in the solution explorer. If you save files in other places they won't be tracked.

The way to do it is to place the .tst file where you want the rendererd files.

**Comment by stombeur** [comment]
OK, it's just that the rendered files need to be in an asp.net 5 project and I don't think typewriter supports that yet. I've got the normal way to work and I just copy the files over to the other project.

Anyway, great job on the extension, it's really useful. Thank you!
But you should definitely try out my first comment, with the .. there are weird folders created in the VS project and it's a risk if you then delete these folders.

**Comment by frhagn** [comment]
Thanks @stombeur! I'll have a look at it.
