### ISSUE TITLE
Does not work in Windows Class Library

### ISSUE THREAD

**Issue by mrzappit** [frhagn/Typewriter#73]
Is there any way to make this work in a Windows Class Library?  I got it to work in a Web project, but if I have a Windows Class Library project, it doesn't do anything.  I just keep getting unhandled exceptions.

**Comment by frhagn** [comment]
Hi @mrzappit, 
Could you provide some more info on this issue? It should work the same in a Windows Class Library as in a Web Project.

What exceptions are you getting? 
Which Visual Studio version are you using?
What does the tst template look like?

**Comment by mrzappit** [comment]
I apologize.  I couldn't figure out why the same template was working for a Web project but not for a Windows Class Library, so I assumed that was the problem.  It turns out, we just weren't properly setting the location of the source files.
