### ISSUE TITLE
Option to force template rendering

### ISSUE THREAD

**Issue by floatas** [frhagn/Typewriter#74]
Now and then I find that my rendered files are out of date, and only way to make them re-render is to update template (by adding new line). It doesn't happen so often and is hard to debug. I think option to force rendering would be nice, maybe right click on template ?
I could help to implement this feature, but would like to get some input on it.

**Comment by frhagn** [comment]
Hi @floatas,
Sounds like a great idea, and awesome if you'd like to help implement it!
Right-click on a tst file in the Solution Explorer and then "Render Template" from the context menu.

**Comment by FreeFrags** [comment]
Created a PR for this feature:
https://github.com/frhagn/Typewriter/pull/84

**Comment by frhagn** [comment]
Merged.

**Comment by frhagn** [comment]
Released in 1.3.2
