### ISSUE TITLE
Set the path of the generated ts files

### ISSUE THREAD

**Issue by VaronisDNMacClient** [frhagn/Typewriter#77]
Hi,
I've seen that **TypeWriter.Configuration.Settings** enables you to manipulate the generated files' filename.

But is there any way to set the path of the generated files?
Currently I'm referencing my **tst** from outside of the project, and I would like the generated ts to be placed besides it (and not in my project folder).

Thanks

**Comment by frhagn** [comment]
Hi @VaronisDNMacClient,
Saving output files outside the project is not supported. (See issue #71 for more info in this).
Maybe you could try to use some kind of file system watcher to copy the rendered files to the external folder?
