### ISSUE TITLE
Error rendering template ... if enum is type of byte

### ISSUE THREAD

**Issue by specialwork** [frhagn/Typewriter#78]
Getting the following error, if the enum is type of byte.

Error rendering template. Cannot get identifier 'Value'. Ein Aufrufziel hat einen Ausnahmefehler verursacht.

    public enum ValueStatus : byte
    {
        /// <summary>
        ///     Missing value.
        /// </summary>
        F = 0x01,

        /// <summary>
        ///     Disturbed value.
        /// </summary>
        G = 0x02,

        /// <summary>
        ///     Temporary value.
        /// </summary>
        V = 0x03,

        /// <summary>
        ///     Estimated value.
        /// </summary>
        E = 0x04,

        /// <summary>
        ///     True / Valid value.
        /// </summary>
        W = 0x05,

        /// <summary>
        ///     Manually changed value.
        /// </summary>
        M = 0x06
    }

Kind regards,
Thomas van Veen

**Comment by frhagn** [comment]
Hi @specialwork,
The underlying problem is the use of hexadecimal values. I'll fix this in the next release.
Meanwhile you can use interger values instead e.g.
```CSharp
public enum ValueStatus : byte
{
    F = 1,
    G = 2,
    V = 3,
    E = 4,
    W = 5,
    M = 6
}
```

**Comment by specialwork** [comment]
Hi frhagn, thank you fort your Support. I'll try using integer values instand of hex values.

**Comment by frhagn** [comment]
No problem.
I've added support for hexadecimal enum values in Typewriter 1.3 so if you upgrade to the latest version it should work without changing to integers.
