### ISSUE TITLE
Set Build Action for the generated files

### ISSUE THREAD

**Issue by VaronisDNMacClient** [frhagn/Typewriter#81]
Is it possible to set the build action for the generated files?
The **tst** file is set with *'None'* but the generated **ts** files are set with *'TypeScriptCompile'*
Any way to set them also to *'None'* in the **tst** configuration?

**Comment by frhagn** [comment]
No, it's not possible to configure the build action at the moment (1.3.1).
I'll look at adding support for it in a future version.
