### ISSUE TITLE
Object reference not set to an instance of an object. Template:...

### ISSUE THREAD

**Issue by JohnGalt1717** [frhagn/Typewriter#82]
Hi there. I added Typewritter to my .NET 4.6 project (As an asideTypewriter tst files don't show up as something you can add to a Portable library which is a common thing for DTOs). I changed nothing and the project was a standard project, not portable and the above error occurs as soon as the file is saved as is.
Nothing gets generated. I'm using VS.net 2015 Update 1.

**Comment by frhagn** [comment]
That's wierd.. There should be an error log in the output window, could you post it here?

**Comment by frhagn** [comment]
Cannot reproduce
