### ISSUE TITLE
IncludeReferencedProjects not working?

### ISSUE THREAD

**Issue by FreeFrags** [frhagn/Typewriter#83]
Hi 
I was trying to generate TS files for my current project and a project which is referenced.

this is my configuration so far no errors shown but no files are generated. Im aware that i better set a proper filter as i will now generate files for all classes in referenced and my own project. 

But this configuration doesnt seem to generate the TS for my referenced projects any ideas?

```typescript
${
    // Enable extension methods by adding using Typewriter.Extensions.*
    using Typewriter.Extensions.Types;

    // Uncomment the constructor to change template settings.
    Template(Settings settings)
    {
        settings.IncludeCurrentProject();
        settings.IncludeReferencedProjects();
    }

    // Custom extension methods can be used in the template by adding a $ prefix e.g. $LoudName
    string LoudName(Property property)
    {
        return property.Name.ToUpperInvariant();
    }
}
module app {
 
    $Classes(*)[
    export class $Name {
        $Properties[ 
        // $LoudName 
        public $name: $Type = $Type[$Default];]
    }]
}
```

**Comment by frhagn** [comment]
Hi @FreeFrags,
I just tried your template and it works fine... 
Could you provide som info on your environment? E.g. Visual Studio version, Project type, Typewriter version etc.
Is there any log info in the Output window if you select "Typewriter" in "Show output from"?

**Comment by FreeFrags** [comment]
Im using VS 2015 professional
Typewriter version 1.3.1

My C# project is not in the same solution as my TS project but only referenced should this work?

**Comment by frhagn** [comment]
Ok, I think that's the issue... All projects must be in the same solution since Typewriter reads the metadata from the C# source files and not the compiled dll:s.

**Comment by FreeFrags** [comment]
Allright thats too bad :) but thank you for the quick reply

**Comment by frhagn** [comment]
No problem :)
