### ISSUE TITLE
Stop Typewriter rendering templates when a file is saved

### ISSUE THREAD

**Issue by LeeCheneler** [frhagn/Typewriter#86]
There may already be a way to do this but I can't find it. It would be useful if we could disable the rendering of templates when files in the project are saved? A checkbox in a menu somewhere, or a right click on the template with an option to toggle the auto rendering.

**Comment by frhagn** [comment]
There's no way to disable the automatic rendering at the moment (other than disabling the extension in the Extensions and Updates window).

**Comment by JulioGold** [comment]
I did an PR to add this feature.

#91

**Comment by frhagn** [comment]
Included in 1.4. Thanks @JulioGold!

**Comment by JulioGold** [comment]
Thanks
