### ISSUE TITLE
Add support for generics <T>

### ISSUE THREAD

**Issue by cmorgado** [frhagn/Typewriter#87]
Using a class such as

 public class ApiPagedResultBase < T >
    {
        public bool HasError { get; set; } = false;
        public string Message { get; set; } = string.Empty;
        public IEnumerable < T > Result { get; set; }
        public bool HasMore { set; get; }
        public int Total { set; get; }
    }

Will fail.
The latest Typescript allows generics ;)

**Comment by frhagn** [comment]
Typewriter already supports generics. You can use `$TypeParameters` and `$TypeArguments` to access the generics e.g.
```
$Classes(*Model)[
class $Name$TypeParameters { 
    $Properties[
        public $Name: $Type;]
}]
```
will output
```
class ApiPagedResultBase<T> { 
    
        public HasError: boolean;
        public Message: string;
        public Result: T[];
        public HasMore: boolean;
        public Total: number;
}
```

**Comment by cmorgado** [comment]
PERFECT!
