### ISSUE TITLE
Add Support for referenced libraries

### ISSUE THREAD

**Issue by cmorgado** [frhagn/Typewriter#89]
Hi,
I usually put my models in a PCL (or similar) so I can share them with other platforms.
As such they don't fire the generated template...
It would be nice that when we choose "Render Template" (from the last version) it would look for the filter as a class not at a file.... or sort ... so it generates the TS files from the models I referenced from the PCL ;)

I hope I explained it right...

**Comment by frhagn** [comment]
Hi @cmorgado,
I'm looking at implementing support for this scenario. It looks promising, but it'll probably be a while before it's done.

**Comment by fernandocode** [comment]
Hi @frhagn ,
Do you have any plans or alternative to be able to generate TS file from Project Libraries?
This would be a great help as it is a good practice to keep Models in a seperated module to be shared between different projects of different platforms.

**Comment by frhagn** [comment]
I'm working on support for this but it's still early so I don't know when it'll be done, hopefully soon.

**Comment by fernandocode** [comment]
Sorry @frhagn ,
I was precipitated in my comment, that is supported, only there was no finding as. I have to set the configuration `IncludeProject` property with the name of my library project reference::

```
${
    Template(Settings settings)
    {
        settings
            .IncludeCurrentProject()
            .IncludeProject("Base.Model");
    }
}
```

In my case I am using Class Library as referenced project. =D

**Comment by cmorgado** [comment]
I've tried this but it does not generate any TS from the POCO in the
eCommerce.Domain class library ...  can you give me an hint please

${
    Template(Settings settings)
    {
        settings
            .IncludeCurrentProject()
            .IncludeProject("eCommerce.Domain");
    }}
 $Classes(*.eCommerce.Domain.Models*)[export class
$Name$TypeParameters { $Properties[
    $Name: $Type;]


 constructor( $Properties[
    $name: $Type ][,]){
    $Properties[
        this.$Name=$name;]
    }
   }]


Best regards
Cristóvão Morgado
pt.linkedin.com/in/cmmorgado/
github.com/cmorgado

   -

**Comment by fernandocode** [comment]
Hey @cmorgado ,

What an example of class and its namespace in `eCommerce.Domain` as your filter seems odd: `$ Classes (* eCommerce.Domain.Models *.)`, There is something before `*.eCommerce`? The `eCommerce.Domain` project is in the same solution of its main project where the * .tst set?

My template file (models.tst):

```
${
    Template(Settings settings)
    {
        settings
            .IncludeCurrentProject()
            .IncludeProject("Base.Model");
    }
}

module Models {
$Classes(Base.Model.*)[
    export class $Name {
        $Properties[
            public $name: $Type;]
    }]
}
```

Example of class in Project Class Library `Base.Model` `(Person.cs`):

```
namespace Base.Model.Entities
{
    public class Person
    {
        public virtual long Id { get; set; }
        public virtual string Name{ get; set; }
    }
}
```

This generates in my web project as follows (Person.ts):

```
module Models {

    export class Person {
        
            public id: number;
            public name: string;
    }
}
```

See how is its structure, name Project Class Library, and its namespace.

I'm using:
- Version 1.3.2 of Typewriter;
- Visual Studio 2015 Update 2;
- My project is in ASP.NET 5, not if it is relevant to this case.

I hope this information helps you! = D

**Comment by frhagn** [comment]
Just to be clear here:
Rendering ts classes from referenced projects in the same solution are supported by using any combination of:
```
settings.IncludeCurrentProject()
settings.IncludeReferencedProjects()
settings.IncludeProject("Base.Model");
```
Rendering classes from referenced asseblies that's not a part of the same solution are not supported (yet).

**Comment by fernandocode** [comment]
@frhagn 

It can be something of my environment, but in my case the following two options did not work:

```
settings.IncludeCurrentProject ()
settings.IncludeReferencedProjects ()
```

Only `settings.IncludeProject("Base.Model")` worked. Therefore I recommended and quoted to @cmorgado .

But this plugin is great. ;)

**Comment by cmorgado** [comment]
It's working now...

Just the "render template" context item menu is not firing .. I had to
"re-save" the .cs and then it generated !

FANTASTIC!

Best regards
Cristóvão Morgado
pt.linkedin.com/in/cmmorgado/
github.com/cmorgado

   -

**Comment by cmorgado** [comment]
It's now working 100%

**Comment by kreloses** [comment]
settings.IncludeProject only works for projects within the solution, and not for referenced assemblies. I assume it's not implemented yet? Otherwise great tool thanks. 

**Using** 
VS2015: 14.0.25123.00 (update 2)
Typewriter: 1.7.2

**Comment by RolfVeinoeSorensen** [comment]
This IncludeProject is fantastic. Thank you for this awsome extension!

**Comment by githubkush** [comment]
Apologies if I'm adding this to an old thread but wanted to ask if it was possible to limit the **"IncludeProject"** functionality to a specific **Namespace**

**Comment by Beej126** [comment]
You probably already considered and I understand it feels more overhead but just in case: you can filter the classes by namespace... see example in “getting started”

**Comment by Etchelon** [comment]
Still no ability to get types from referenced assemblies (ie nuget packages)?
