### ISSUE TITLE
Only one source file can be active for any one template file in the case multiple templates need types from a single source file

### ISSUE THREAD

**Issue by kamranayub** [frhagn/Typewriter#92]
Given a single source file with two types:
 
**Foo.cs**
```c#
public class MyModel {
}

enum FooEnum {
}
```

If you create two templates:

**Enums.tst**
```
module foo {

    $Enums(*)[
    export enum $Name {
        $Values[
        $Name = $Value][,]
    }]
}
```

**Models.tst**
```
module foo {

    $Classes(*Model)[
    export interface $Name {
        $Properties[
        $Name: $Type;]
    }]
}
```

Then Typewriter will not create two separate `Foo.ts` and `Foo (1).ts` files due to the source file containing two types both templates reference, instead only one template at a time will generate a `Foo.ts` file.

**Comment by LeeCheneler** [comment]
There are two ways in which you can overcome this as I would suggest that the behaviour you are describing is expected and correct.

### 1) Derive the proper name of the file yourself and save them in separate files

```sh
Template(Settings settings)
{
    settings.OutputFilenameFactory = file =>
    {
        var modelClass = file.Classes.First();
        return $"twModels/{modelClass.name}.ts";
    };
}
```

This sets the output file name to the first classes name it finds in the file. The possibilities for what you can do here are plentiful and you can easily accommodate a lot of scenarios and naming formula etc. You would do similar in the enum typewriter template file too to derive a better file name for it.


### 2) Put them both in the same file with a single template

```sh
module foo {
    $Enums(*)[
    export enum $Name {
        $Values[
        $Name = $Value][,]
    }]

    $Classes(*Model)[
    export interface $Name {
        $Properties[
        $Name: $Type;]
    }]
}
```

This would output a single file `Foo.ts` with your enum and your class in.

I would however not have a class and an enum in the same C# file, you should try to keep your files atomic, 1 class or 1 struct or 1 enum etc. Straight away this solves your problem. This issue arising could be used as a good indicator that your file structure and purposing is a little off.

**Comment by kamranayub** [comment]
Thanks, I just used the filename factory for another project so I will go
with that!

**Comment by LeeCheneler** [comment]
@frhagn I think this issue can be closed :)
