### ISSUE TITLE
Multiple selections? Blacklisting?

### ISSUE THREAD

**Issue by BKer** [frhagn/Typewriter#95]
Hi,

Is it possible to blacklist or have multiple selections when using $Classes ?
For example we have:
A.B.a
A.B.b
A.B.c
And I would like to include A.B.a and A.B.c. How would I go about this?
It would be nice to be able to do something like [A.B.* !A.B.b] or like [A.B.a, A.B.c]
Is anything like this possible?

I hope it's clear what I meant. I'm currently on my phone so not going to write huge amounts of texts. If something is not clear just let me know. Thanks in advance!

**Comment by frhagn** [comment]
Hi @BKer,
You can use lambda expressions to filter out the classes you want, e.g. 
```
$Classes(c => c.Namespace == "A.B" && c.Name != "b")[...]
```

**Comment by wonkim00** [comment]
You can have very fine-grained control over which classes you want to generate typescript for by defining your own attribute class and marking just the classes you want to export. 

```
   /// <summary>
   /// Marks C# (enum|class|interface) for export as equivalent type in Typescript so it can be used in the web/javascript application.
   /// </summary>
   [AttributeUsage(AttributeTargets.Enum | AttributeTargets.Class | AttributeTargets.Interface)]
   public class ExportToTypescriptAttribute : Attribute
   {
      // Doesn't need anything in it; just its presence is enough.
   }

   [ExportToTypescript]
   public class SimpleModel
   {
      public string Name { get; set; }
      public bool IsFoo { get; set; }
      public int BarCount { get; set; }
   }
```

Then in your Typewriter template:
`$Classes([SynExportToJavascript])`

**Comment by BKer** [comment]
Hi,

Thank you both for your swift reply :)
