### ISSUE TITLE
Supported conditional operations in Template .tst!

### ISSUE THREAD

**Issue by fernandocode** [frhagn/Typewriter#96]
For example, I'm trying to add the Inheritance of the C# classes in Typescript in which has $BaseClass, but need to do a conditional in my template for cases of not have $BaseClass, what I have today is as follows:

```
module Models {
$Classes(Base.Model.*)[
    export class $Name extends $BaseClass[$Name] {
        $Properties[
            public $name: $Type;]
    }]
}
```

Where `BaseModel.cs` and `Person.cs `classes below:

```
namespace Base.Model.Core
{
    public class BaseModel : IBaseModel
    {
        public virtual long Id { get; set; }
    }
}
```

```
namespace Base.Model.Entities
{
    public class Person : Core.BaseModel
    {
        public string Name { get; set; }
    }
}
```

They are generated in Typescript this way:

`BaseModel.ts`
```
module Models {

    export class BaseModel extends  {
        
            public id: number;
    }
}
```

`Person.ts`
```
module Models {

    export class Person extends BaseModel {
        
            public name: string;
    }
}
```

As you can see I need a conditional not to add extends there in the case of BaseModel.ts, since he has no inheritance.
Is there something to this? Or it would have to be an improvement?

**Comment by frhagn** [comment]
$BaseClass itself is conditional so you can write something like this to get the result you want:
```
module Models {
$Classes(Base.Model.*)[
    export class $Name$BaseClass[ extends $Name] {
        $Properties[
            public $name: $Type;]
    }]
}
```

And if you want to include properties from the base class:
```
module Models {
$Classes(Base.Model.*)[
    export class $Name$BaseClass[ extends $Name] {
        $BaseClass[$Properties[
            public $name: $Type;]]
        $Properties[
            public $name: $Type;]
    }]
}
```

**Comment by frhagn** [comment]
You can also write a custom method to add conditions.
```
${
    bool HasBaseClass(Class c)
    {
        return c.BaseClass != null;
    }
}
module Models {
$Classes(Base.Model.*)[
    $HasBaseClass[
        // true
    ][
        // false
    ]
]
}
```

**Comment by fernandocode** [comment]
Worked perfectly.

Thank you!

Is there any documentation or reference something about this Template (.tst). Can not find anything about this template, it is something developed specifically for this library?

There are some Q&A channel for the community that uses this library? As an example [StackOverflow ](http://stackoverflow.com/)([I noticed that the tag is not present there](http://stackoverflow.com/questions/tagged/typewriter))?

**Comment by frhagn** [comment]
No problem :)
Documentation is available at http://frhagn.github.io/Typewriter/
