### ISSUE TITLE
can you add gulp support for typewriter

### ISSUE THREAD

**Issue by harishrathi** [frhagn/Typewriter#99]
This is a feature request. Can we have it a gulp plugin for this. So i can use different tst files with different plugins + integrate it with other gulp plugins like concat etc. so have a much better build system.

Btw, thanks a lot for this freakingly awesome plugin

**Comment by harishrathi** [comment]
I was looking at the code... but could not find a point where i can pass the cs file path & the tst file path and get an output file, can you please help me with that

**Comment by frhagn** [comment]
Interesting idea, but Typewriter depends on Visual Studio so it can't be run from outside sources like Gulp. Maybe in a future version...

**Comment by harishrathi** [comment]
the library which does the basic work... converting cs to ts with some options is independent. I would be interested to start working on this, but would need your help, may be a small code walk thru or which test cases would help me in understanding the part i am interested in. Why I am interested to integrate it with gulp or grunt is because I can combine it with other plugins and get the desired result like single output file or ts location different than the tst location. etc...
